CREATE TABLE recruiting_backfills (
  backfill_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  work_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  requested_by VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  target_type VARCHAR(64) CHARACTER SET ascii NOT NULL,
  target_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  backfill_mode VARCHAR(32) CHARACTER SET ascii NOT NULL,
  range_start DATETIME(6) NOT NULL,
  range_end DATETIME(6) NOT NULL,
  fields_json JSON NOT NULL,
  recipe_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  recipe_version BIGINT UNSIGNED NOT NULL,
  policy_version BIGINT UNSIGNED NOT NULL,
  backfill_status VARCHAR(32) CHARACTER SET ascii NOT NULL,
  preview_cursor VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
  previewed_items BIGINT UNSIGNED NOT NULL,
  preview_accumulator VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  preview_hash VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  succeeded_items BIGINT UNSIGNED NOT NULL,
  accepted_gap_items BIGINT UNSIGNED NOT NULL,
  failed_items BIGINT UNSIGNED NOT NULL,
  version BIGINT UNSIGNED NOT NULL,
  state_json JSON NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (backfill_id),
  UNIQUE KEY uq_recruiting_backfill_work (work_id),
  KEY ix_recruiting_backfill_target (target_type, target_id, created_at, backfill_id),
  KEY ix_recruiting_backfill_status (backfill_status, updated_at, backfill_id),
  CONSTRAINT fk_recruiting_backfill_work FOREIGN KEY (work_id) REFERENCES recruiting_works(work_id),
  CONSTRAINT fk_recruiting_backfill_recipe FOREIGN KEY (recipe_id, recipe_version) REFERENCES recruiting_recipes(recipe_id, recipe_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recruiting_backfill_items (
  backfill_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  item_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  job_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  job_version BIGINT UNSIGNED NOT NULL,
  refresh_generation BIGINT UNSIGNED NOT NULL,
  source_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_version BIGINT UNSIGNED NOT NULL,
  detail_url VARCHAR(2048) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  input_detail_version_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
  input_artifact_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
  input_observed_at DATETIME(6) NULL,
  work_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
  output_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
  item_status VARCHAR(32) CHARACTER SET ascii NOT NULL,
  failure_class VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
  version BIGINT UNSIGNED NOT NULL,
  state_json JSON NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (backfill_id, item_id),
  UNIQUE KEY uq_recruiting_backfill_item_work (work_id),
  KEY ix_recruiting_backfill_item_status (backfill_id, item_status, item_id),
  KEY ix_recruiting_backfill_item_job (job_id, backfill_id),
	KEY ix_recruiting_backfill_item_input (input_detail_version_id, backfill_id, item_id),
  CONSTRAINT fk_recruiting_backfill_item_batch FOREIGN KEY (backfill_id) REFERENCES recruiting_backfills(backfill_id),
  CONSTRAINT fk_recruiting_backfill_item_job FOREIGN KEY (job_id) REFERENCES recruiting_source_jobs(job_id),
	CONSTRAINT fk_recruiting_backfill_item_detail FOREIGN KEY (input_detail_version_id) REFERENCES recruiting_job_detail_versions(detail_version_id),
  CONSTRAINT fk_recruiting_backfill_item_work FOREIGN KEY (work_id) REFERENCES recruiting_works(work_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recruiting_backfill_outputs (
  output_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  backfill_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  item_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  job_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  backfill_mode VARCHAR(32) CHARACTER SET ascii NOT NULL,
  content_hash VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  output_artifact_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  input_detail_version_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
  input_artifact_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL,
  recipe_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  recipe_version BIGINT UNSIGNED NOT NULL,
  fields_json JSON NOT NULL,
  derived_from_observed_at DATETIME(6) NULL,
  refetched_at DATETIME(6) NULL,
  claims_historical_snapshot BOOLEAN NOT NULL DEFAULT FALSE,
  output_json JSON NOT NULL,
  state_json JSON NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (output_id),
  UNIQUE KEY uq_recruiting_backfill_output_item (backfill_id, item_id),
  KEY ix_recruiting_backfill_output_job (job_id, created_at, output_id),
  CONSTRAINT fk_recruiting_backfill_output_item FOREIGN KEY (backfill_id, item_id) REFERENCES recruiting_backfill_items(backfill_id, item_id),
  CONSTRAINT fk_recruiting_backfill_output_job FOREIGN KEY (job_id) REFERENCES recruiting_source_jobs(job_id),
  CONSTRAINT fk_recruiting_backfill_output_recipe FOREIGN KEY (recipe_id, recipe_version) REFERENCES recruiting_recipes(recipe_id, recipe_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
