(()=>{
 const desiredChecked=value=>/^(true|yes|1|是)$/i.test(String(value??'').trim());
 const datePickerValue=(value,fieldLabel='')=>{const desired=String(value??'').trim();if(!/^\d{4}-\d{2}$/.test(desired))return desired;const [year,month]=desired.split('-').map(Number);if(month<1||month>12)return desired;const end=/(?:结束|截止|毕业|终止|\bend\b|\buntil\b)/i.test(String(fieldLabel??''));return`${desired}-${String(end?new Date(Date.UTC(year,month,0)).getUTCDate():1).padStart(2,'0')}`};
 const nativeParseSignal=text=>/(解析|导入|一键|自动|智能).{0,12}(简历|履历)|(简历|履历).{0,12}(解析|导入|填充|填写|更新)|(parse|import|autofill).{0,12}(resume|cv)|(resume|cv).{0,12}(parse|import|autofill)/i.test(String(text??''));
 const nativeParseAutomaticSignal=text=>/(上传|导入).{0,20}(后|成功后).{0,16}(自动|智能).{0,12}(解析|填充|填写)|(自动|智能).{0,12}(解析|填充|填写).{0,20}(上传|导入)|(automatically|auto).{0,12}(parse|fill|import).{0,16}(after|on).{0,12}(upload|select)/i.test(String(text??''));
 const nativeParseConfirmSignal=text=>/(开始|确认|立即|使用|覆盖).{0,10}(解析|导入|填充|填写)|(上传|导入).{0,6}(并|后)?(?:自动|智能)?(解析|填充|填写)|(解析|导入|填充|填写).{0,10}(并覆盖|并填充|并填写)|(parse|import|upload).{0,10}(and|then)?\s*(parse|autofill)|(parse|import|autofill).{0,10}(now|resume|cv)/i.test(String(text??''));
 const nativeParseBusySignal=text=>/正在.{0,8}(解析|导入)|(解析|导入|处理)中|(parsing|importing|processing).{0,8}(resume|cv)?/i.test(String(text??''));
 const applicationStartSignal=text=>/^(?:(?:立即|马上|现在|去|我要)\s*)?(?:申请|投递|应聘)(?:(?:该|此)\s*)?(?:职位|岗位|简历)?$|^apply(?:\s+now|\s+for\s+(?:this\s+)?(?:job|position))?$/i.test(String(text??'').replace(/\s+/g,' ').trim());
 const pageSurfaceFrom=({pathname='',hash='',hasApplicationEntry=false,hasResumeEntry=false,hasResumeForm=false}={})=>{const route=`${pathname}${hash}`,detailRoute=/(?:^|[\/#])(?:postDetail|posDetail|position|positions|job|jobs|detail)(?:[\/?#]|$)/i.test(route),resumeRoute=/(?:^|[\/#])(?:apply|application|resume|profile|personalCenter|form|edit)(?:[\/?#]|$)/i.test(route);return hasApplicationEntry?'entry_surface':hasResumeEntry||hasResumeForm?'resume_surface':resumeRoute?'resume_surface':detailRoute?'entry_surface':'unknown'};
 const authenticationRouteSignal=value=>{try{const url=new URL(String(value),'https://cvmax.invalid');return/(?:^|[\/#])(?:login|signin|register)(?=\/|\?|#|$)/i.test(`${url.pathname}${url.hash}`)}catch{return false}};
 const resumePrerequisiteSignal=text=>/^(创建完整简历|创建在线简历|完善简历|完善在线简历|补充简历|create (a )?(complete )?(resume|cv)|complete (your )?(resume|cv))$/i.test(String(text??'').replace(/\s+/g,' ').trim());
 const resumePrerequisitePageSignal=text=>/(请先|尚未|还未|需要|必须).{0,16}(上传|创建|完善|补充).{0,10}(简历|履历).{0,16}(申请|投递|职位|岗位)|(简历|履历).{0,16}(上传|创建|完善|补充).{0,16}(后|才可|才能).{0,10}(申请|投递)|(upload|create|complete).{0,16}(resume|cv).{0,16}(before|to).{0,12}(apply|application)/i.test(String(text??'').replace(/\s+/g,' ').trim());
 const resumeEditSignal=text=>/^(编辑|编辑简历|完善|完善简历|前往设置|前往完善|去完善|去创建|edit|edit resume|complete resume|go to (?:settings|profile))$/i.test(String(text??'').replace(/\s+/g,' ').trim());
 const resumeNavigationSignal=text=>resumePrerequisiteSignal(text)||resumeEditSignal(text);
 const dialogStateFromText=(text,{hasPassword=false,hasCaptcha=false}={})=>hasCaptcha?'captcha':hasPassword?'login':/(简历|履历).{0,24}(完整度|完善|创建|补充)|(完整度|完善|创建|补充).{0,24}(简历|履历)|(resume|cv).{0,24}(complete|create|profile)/i.test(String(text??''))?'resume_prerequisite':'unknown';
 const boundedDialogText=(text,max=600)=>String(text??'').replace(/\s+/g,' ').trim().slice(0,max);
 const finalSubmitSignal=text=>/(提交申请|确认投递|立即投递|完成申请|确认申请|submit application|complete application)/i.test(String(text??''));
 const workflowCanAdvance=({surfaceKind,formStage,applicationFieldCount=0,requiredComplete=false,valid=true,errorCount=0,controls=[]}={})=>{if(errorCount>0||valid!==true)return false;if(applicationFieldCount>0)return requiredComplete===true;const safeNext=controls.filter(control=>control?.kind==='next'&&control.safe===true);return surfaceKind==='resume_surface'&&formStage==='apply'&&safeNext.length===1};
 const equivalentStartControl=(candidates,textOf)=>{if(!candidates.length)return null;const labels=new Set(candidates.map(item=>String(textOf(item)??'').replace(/\s+/g,' ').trim().toLowerCase()));return labels.size===1?candidates[0]:null};
 const outsideViewport=(rect,width,height)=>rect.bottom<=0||rect.right<=0||rect.top>=height||rect.left>=width;
 const floatingPanelPosition=(target,panel,viewport,{gap=14,margin=12}={})=>{const left=Math.max(margin,viewport.width-panel.width-margin),below=target.bottom+gap,above=target.top-gap-panel.height,fitsBelow=below+panel.height<=viewport.height-margin;return{left,top:fitsBelow?below:Math.max(margin,above),placement:fitsBelow?'below':'above'}};
 const sectionControlDescriptor=({text='',href='',role='',currentURL=''})=>{
  const label=String(text).replace(/\s+/g,' ').trim();if(!label||label.length>80)return null;
  const normalizedRole=String(role).toLowerCase(),sectionKey=`navigation:${sectionMarker(label)}`;
  if(normalizedRole==='tab')return{sectionKey,label,target:null};
  if(!href)return null;
  try{const current=new URL(currentURL),target=new URL(href,current);if(target.origin!==current.origin||target.pathname!==current.pathname||target.search!==current.search||!target.hash||target.hash.startsWith('#/'))return null;return{sectionKey,label,target:target.hash}}catch{return null}
 };
 const sectionMarker=value=>String(value??'').replace(/[＊*：:]+$/g,'').replace(/\s+/g,' ').trim().toLowerCase();
 function sectionCandidatesFor(element,clean,nodes=null,{limit=12}={}){
  const root=element?.ownerDocument;if(!root?.querySelectorAll)return[];
  const ownText=node=>clean(node.childNodes?[...node.childNodes].filter(child=>child.nodeType===3).map(child=>child.textContent).join(' '):node.textContent),all=nodes??[...root.querySelectorAll('*')],result=[],seen=new Set(),add=(text,source)=>{const label=String(text??'').replace(/\s+/g,' ').trim();if(!label||label.length>40||/[\r\n]/.test(label))return;const key=`${source}:${sectionMarker(label)}`;if(seen.has(key))return;seen.add(key);result.push({key,label,source})};
  for(let node=element?.parentElement,depth=0;node&&depth<7;node=node.parentElement,depth++){
   const explicit=node.getAttribute?.('data-section')||node.getAttribute?.('aria-label');if(explicit)add(explicit,'attribute');
   const heading=node.querySelector?.(':scope > h1,:scope > h2,:scope > h3,:scope > h4,:scope > [role="heading"],:scope > [class*="title"]');if(heading)add(clean(heading.textContent),'heading');
  }
  const navigationLabels=[...new Set(all.filter(node=>node.matches?.('a[href],[role="tab"]')).filter(node=>node.getAttribute?.('role')==='tab'||String(node.getAttribute?.('href')??'').startsWith('#')).map(node=>clean(node.textContent)).filter(label=>label.length>=2&&label.length<=40))];
  if(navigationLabels.length){const sectionHeading=all.filter(node=>node!==element&&!node.contains?.(element)&&(node.compareDocumentPosition?.(element)&4)).reverse().map(node=>ownText(node)).find(text=>navigationLabels.some(label=>text===label||text.startsWith(label)&&text.length<=label.length+80));if(sectionHeading){const label=navigationLabels.find(candidate=>sectionHeading===candidate||sectionHeading.startsWith(candidate));add(label,'heading')}}
  const preceding=all.filter(node=>node!==element&&!node.contains?.(element)&&(node.compareDocumentPosition?.(element)&4)).map(node=>{const direct=ownText(node),fallback=!direct&&node.children?.length<=1?clean(node.textContent):'';return direct||fallback}).filter(text=>text&&text.length<=40).slice(-Math.max(limit*3,24)).reverse();
  for(const text of preceding)add(text,'heading');
  return result.slice(0,limit);
 }
 function leafOptions(candidates){return candidates.filter(candidate=>!candidates.some(other=>other!==candidate&&candidate.contains(other)))}
 function nearestOption(anchor,candidates){if(candidates.length===1)return candidates[0];const a=anchor.getBoundingClientRect(),center=rect=>[rect.left+rect.width/2,rect.top+rect.height/2],ac=center(a),ranked=candidates.map(item=>{const point=center(item.getBoundingClientRect());return{item,distance:(point[0]-ac[0])**2+(point[1]-ac[1])**2}}).sort((x,y)=>x.distance-y.distance);return ranked.length&&(!ranked[1]||ranked[0].distance+1<ranked[1].distance)?ranked[0].item:null}
 function topmostOption(doc,candidates){if(!candidates.length)return null;for(const candidate of candidates){const rect=candidate.getBoundingClientRect(),hits=doc.elementsFromPoint(rect.left+rect.width/2,rect.top+rect.height/2);for(const hit of hits){const matches=candidates.filter(item=>item===hit||item.contains(hit)||hit.contains?.(item));if(matches.length){return matches.find(item=>item.getAttribute?.('role')==='option')??matches[0]}}}return null}
 function equivalentOption(candidates){if(candidates.length<2)return candidates[0]??null;const base=candidates[0].getBoundingClientRect(),same=candidates.every(item=>{const rect=item.getBoundingClientRect();return Math.abs(rect.left-base.left)<1&&Math.abs(rect.top-base.top)<1&&Math.abs(rect.width-base.width)<1&&Math.abs(rect.height-base.height)<1});return same?(candidates.find(item=>item.getAttribute?.('role')==='option')??candidates[0]):null}
 function matchingOptions(candidates,value,clean){const desired=clean(value),exact=candidates.filter(item=>clean(item.textContent)===desired);if(exact.length)return{candidates:exact,normalized:false,matchedValue:desired};const labels=[...new Set(candidates.map(item=>clean(item.textContent)).filter(label=>label.length>=2&&(desired.includes(label)||label.includes(desired))))];return labels.length===1?{candidates:candidates.filter(item=>clean(item.textContent)===labels[0]),normalized:true,matchedValue:labels[0]}:{candidates:[],normalized:false,matchedValue:null}}
	 globalThis.CvMaxContentLogic=Object.freeze({desiredChecked,datePickerValue,nativeParseSignal,nativeParseAutomaticSignal,nativeParseConfirmSignal,nativeParseBusySignal,applicationStartSignal,pageSurfaceFrom,authenticationRouteSignal,resumePrerequisiteSignal,resumePrerequisitePageSignal,resumeEditSignal,resumeNavigationSignal,dialogStateFromText,boundedDialogText,finalSubmitSignal,workflowCanAdvance,equivalentStartControl,outsideViewport,floatingPanelPosition,sectionControlDescriptor,sectionCandidatesFor,leafOptions,nearestOption,topmostOption,equivalentOption,matchingOptions});
})();
