import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash}from'node:crypto';import{Attachments}from'../src/attachments.mjs';
test('attachment scope, version, expiry and byte/type boundaries',()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'cvmax-attachments-'));try{
 const bytes=Buffer.from('Synthetic resume');fs.writeFileSync(path.join(root,'resume.txt'),bytes);const store=new Attachments({root,resourcePrefix:'daemon://device/private-channel/'}),ref={resource:'daemon://device/private-channel/resume.txt',sha256:createHash('sha256').update(bytes).digest('hex'),size:bytes.length,mime:'text/plain',expiresAt:Date.now()+60000};
 assert.equal(store.read(ref).bytes.toString(),bytes.toString());
 for(const change of [{resource:'daemon://device/other-channel/resume.txt'},{resource:'daemon://device/private-channel/%2e%2e/resume.txt'},{expiresAt:0},{size:1},{sha256:'0'.repeat(64)},{mime:'application/pdf'}])assert.throws(()=>store.read({...ref,...change}));
 fs.symlinkSync('/etc/hosts',path.join(root,'escape.txt'));assert.throws(()=>store.read({...ref,resource:'daemon://device/private-channel/escape.txt'}),/outside/);
 fs.writeFileSync(path.join(root,'resume.txt'),'changed');assert.throws(()=>store.read(ref),/changed/);
 }finally{fs.rmSync(root,{recursive:true,force:true})}
});
test('a saved resume source is copied into an isolated non-expiring resume path',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'cvmax-resume-source-'));try{const bytes=Buffer.from('%PDF-saved'),source=path.join(root,'staged.pdf');fs.writeFileSync(source,bytes);const store=new Attachments({root,resourcePrefix:'private:'}),ref={resource:'private:staged.pdf',sha256:createHash('sha256').update(bytes).digest('hex'),size:bytes.length,mime:'application/pdf',expiresAt:Date.now()+60_000},saved=store.persistResume(ref,'resume-one',1),repeated=store.persistResume(ref,'resume-one',1),read=store.read(saved);assert.deepEqual(repeated,saved);assert.equal(saved.scope,'resume');assert.equal(saved.expiresAt,undefined);assert.equal(read.bytes.toString(),bytes.toString());assert.match(decodeURIComponent(saved.resource),/resumes\/resume-one\/1\.pdf$/);assert.throws(()=>store.read({...saved,resource:'private:staged.pdf'}),/path_invalid/)}finally{fs.rmSync(root,{recursive:true,force:true})}});
