import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
import {applicationStartObserved, applicationStartSettled, detectBrowserFamily, EXTENSION_PROTOCOL, normalizeEndpoint, normalizeOrigin, normalizeProgress, normalizeSiteBoundary, validateBridgeCommand, validateCurrentCommand, validateOpenCommand, validateToken} from '../extension/protocol.js';
import {bootstrapInteraction,resumeParseConfirmationSignal,resumeReplacementSignal,resumeUploadAcknowledgementSignal} from '../src/interaction-policy.mjs';

const root=path.dirname(fileURLToPath(import.meta.url));

test('month-only resume ranges use the first day for starts and the last day for ends',()=>{const context={globalThis:{},URL};vm.runInNewContext(fs.readFileSync(path.join(root,'../extension/content-logic.js'),'utf8'),context);const value=context.globalThis.CvMaxContentLogic.datePickerValue;assert.equal(value('2023-04','开始日期'),'2023-04-01');assert.equal(value('2023-04','结束日期'),'2023-04-30');assert.equal(value('2024-02','结束时间'),'2024-02-29');assert.equal(value('2023-04-15','结束日期'),'2023-04-15')});

test('extension package connects pages without a separate site-authorization flow',()=>{
 const dir=path.join(root,'../extension'),manifest=JSON.parse(fs.readFileSync(path.join(dir,'manifest.json')));
 assert.equal(manifest.manifest_version,3);assert.equal(manifest.name,'CvMax');
 assert.equal(manifest.version,'0.2.45');
 assert.equal(manifest.permissions.includes('alarms'),true);
 assert.equal(manifest.content_scripts,undefined);
 assert.equal(fs.existsSync(path.join(dir,'assets/cvmax-companion-cutout.png')),true);
 assert.deepEqual(manifest.web_accessible_resources[0].resources,['assets/cvmax-companion-cutout.png']);
 assert.deepEqual(manifest.host_permissions,['<all_urls>']);
 assert.equal(manifest.optional_host_permissions,undefined);
 const background=fs.readFileSync(path.join(dir,manifest.background.service_worker),'utf8');
 const popupCss=fs.readFileSync(path.join(dir,'popup.css'),'utf8');
 const popupHtml=fs.readFileSync(path.join(dir,'popup.html'),'utf8');
 const popupJs=fs.readFileSync(path.join(dir,'popup.js'),'utf8');
 assert.match(popupCss,/\[hidden\]\{display:none!important\}/);
 assert.match(popupHtml,/id="workflow"/);
 assert.match(popupHtml,/处理流程/);
 assert.match(popupHtml,/接下来由你完成/);
 assert.match(popupJs,/progress\?\.workflow/);
 assert.doesNotMatch(popupJs,/你处理剩余内容/);
 assert.match(popupJs,/aria-current/);
 const server=fs.readFileSync(path.join(root,'../src/server.mjs'),'utf8');
 assert.match(server,/timeoutMs:20000,leaseMs:8000/);
 assert.match(server,/coverageItemSchema=\{type:'object',properties:\{controlRef:/);
 assert.match(server,/fieldRef:\{type:'string'\},disposition:/);
 assert.match(server,/enum:\['mapped','no_resume_fact','unsupported'\]/);
 assert.match(server,/required:\['disposition'\],additionalProperties:false/);
 assert.match(server,/interpretationMappingSchema=\{oneOf:/);
 assert.match(server,/required:\['kind','ref','semanticId'\],additionalProperties:false/);
 assert.match(server,/learning_interpret:\['taskId','expectedRevision','observationId','mappings'\]/);
 assert.match(server,/actionVariant\(\['fill','select','choose','check'\],[^\n]*\['fieldRef','factId'\]/);
 assert.match(server,/actionVariant\(\['next','start'\],[^\n]*\['controlRef'\]/);
 assert.match(background,/setInterval\([^]*20_000\)/);
 assert.match(background,/chrome\.alarms\.create\(RECONNECT_ALARM/);
 assert.match(background,/chrome\.alarms\.onAlarm\.addListener/);
 assert.match(background,/import \{[^}]*normalizeOrigin[^}]*\} from '\.\/protocol\.js'/);
	 const evidence=fs.readFileSync(path.join(dir,'evidence.js'),'utf8');
	 const content=fs.readFileSync(path.join(dir,'content.js'),'utf8');
	 const logic=fs.readFileSync(path.join(dir,'content-logic.js'),'utf8'),context={globalThis:{},URL};vm.runInNewContext(logic,context);
	 const executorSource=`${background}\n${evidence}\n${content}\n${logic}`;
	 assert.doesNotMatch(executorSource,/jobs\.bytedance\.com|campus\.sf-express\.com|简历上传成功|上传新简历将替换|resumeUploadSuccess|resumeReplacement/);
 assert.match(content,/个人证件/);
 assert.match(content,/展开 CvMax 实时进度/);
 assert.match(content,/cvmax-companion-cutout\.png/);
 assert.match(content,/cvmaxProgressPosition/);
 assert.match(content,/pointerdown/);
 assert.match(content,/<span class="logo"><img/);
 assert.match(background,/files:\s*\['evidence\.js',\s*'content-logic\.js',\s*'content\.js'\]/);
 assert.match(background,/message\.action !== 'act'/);
 assert.match(background,/Receiving end does not exist\|Could not establish connection/);
 assert.match(background,/ambiguous\/closed response must never replay/);
 assert.match(background,/typeof globalThis\.__cvmaxCommand!=='function'/);
	 assert.match(background,/cvmaxResult:await globalThis\.__cvmaxCommand\(payload\)/);
	 assert.match(background,/cvmaxError:String\(error\?\.message\?\?error\)/);
	 assert.match(background,/receipt\?\.result\?\.cvmaxError/);
 assert.match(background,/if\(receipt\?\.error\)/);
 assert.match(background,/content_execution_failed/);
 assert.match(content,/globalThis\.__cvmaxCommand=command/);
	 assert.match(content,/markActionPhase\(message,'select_started'\)/);
	 assert.match(content,/markActionPhase\(message,'select_retained'\)/);
	 assert.match(content,/parseButtons\.length===1/);
	 assert.match(evidence,/inspectedAncestors/);
	 assert.doesNotMatch(content,/action\.kind==='section'\)\{await new Promise\([^]*const after=observe\(\)/);
	 assert.match(content,/input\.ant-select-search__field/);
	 assert.match(content,/searchInput\.dispatchEvent\(new Event\('input'/);
 assert.match(content,/markActionPhase\(message,'setter_completed'\)/);
 assert.match(content,/markActionPhase\(message,'verified'\)/);
 assert.match(background,/cvmaxActionDiagnostic:diagnostic/);
 assert.match(background,/browser action receipt is the state-machine commit boundary/);
 assert.match(background,/publish\(\)\.catch\(\(\) => \{\}\);\s*return result/);
 assert.match(background,/const CONTENT_GENERATION = crypto\.randomUUID\(\)/);
 assert.match(background,/__cvmaxRequestedGeneration/);
 assert.match(content,/__cvmaxContentGeneration===contentGeneration/);
 assert.equal(context.globalThis.CvMaxContentLogic.desiredChecked('false'),false);
 assert.equal(context.globalThis.CvMaxContentLogic.desiredChecked('是'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.nativeParseSignal('上传简历后自动解析并填写'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.nativeParseSignal('上传附件'),false);
 assert.equal(context.globalThis.CvMaxContentLogic.nativeParseAutomaticSignal('上传成功后，系统将自动解析简历并填充'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.nativeParseAutomaticSignal('点击上传后确认解析简历'),false);
 assert.equal(context.globalThis.CvMaxContentLogic.nativeParseConfirmSignal('确认解析简历'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.nativeParseConfirmSignal('解析并覆盖'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.nativeParseConfirmSignal('是，上传并解析'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.nativeParseConfirmSignal('Upload and parse'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.nativeParseBusySignal('正在解析简历'),true);
	 assert.equal(resumeReplacementSignal('上传新简历将替换现有简历内容，请确认是否继续 取消 继续'),true);
	 assert.equal(resumeReplacementSignal('确认提交申请'),false);
 assert.equal(resumeParseConfirmationSignal('是否根据您上传的附件信息，自动填写至简历详情中？'),true);
 assert.deepEqual(bootstrapInteraction({activeDialog:{text:'是否根据您上传的附件信息，自动填写至简历详情中？'},interactions:[{ref:'no',label:'否，仅上传附件',surface:'dialog',safe:true},{ref:'yes',label:'是，上传并解析',surface:'dialog',safe:true}]},'native_parse'),{kind:'activate',controlRef:'yes',activationMode:'isolated_pointer',expectedPostcondition:'dialog_closed',purpose:'resume_parse_confirmation'});
 assert.equal(context.globalThis.CvMaxContentLogic.applicationStartSignal('立即申请'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.applicationStartSignal('立即投递'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.applicationStartSignal('投递'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.applicationStartSignal('去投递该职位'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.applicationStartSignal('马上应聘此岗位'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.applicationStartSignal('Apply for this position'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.applicationStartSignal('提交申请'),false);
 assert.equal(context.globalThis.CvMaxContentLogic.applicationStartSignal('查看申请记录'),false);
 assert.equal(context.globalThis.CvMaxContentLogic.pageSurfaceFrom({pathname:'/job/detail',hasApplicationEntry:true}),'entry_surface');
 assert.equal(context.globalThis.CvMaxContentLogic.pageSurfaceFrom({pathname:'/job/detail',hasResumeEntry:true}),'resume_surface');
 assert.equal(context.globalThis.CvMaxContentLogic.pageSurfaceFrom({pathname:'/apply',hasResumeForm:true}),'resume_surface');
 assert.equal(context.globalThis.CvMaxContentLogic.authenticationRouteSignal('https://jobs.example/#/register'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.authenticationRouteSignal('https://jobs.example/#/login?next=job'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.authenticationRouteSignal('https://jobs.example/#/jobs/1'),false);
 assert.deepEqual({...context.globalThis.CvMaxContentLogic.floatingPanelPosition({left:120,top:100,bottom:160},{width:300,height:240},{width:1200,height:800})},{left:888,top:174,placement:'below'});
 assert.deepEqual({...context.globalThis.CvMaxContentLogic.floatingPanelPosition({left:1100,top:650,bottom:700},{width:300,height:240},{width:1200,height:800})},{left:888,top:396,placement:'above'});
 assert.equal(context.globalThis.CvMaxContentLogic.resumePrerequisiteSignal('创建完整简历'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.resumePrerequisiteSignal('完善在线简历'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.resumePrerequisiteSignal('上传简历'),false);
 assert.equal(context.globalThis.CvMaxContentLogic.resumePrerequisitePageSignal('请先上传简历再申请职位！ 前往设置'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.resumePrerequisitePageSignal('应聘岗位：软件工程师'),false);
 assert.equal(context.globalThis.CvMaxContentLogic.resumeEditSignal('编辑'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.resumeEditSignal('前往设置'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.resumeEditSignal('确认提交'),false);
 assert.equal(context.globalThis.CvMaxContentLogic.resumeNavigationSignal('前往设置'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.resumeNavigationSignal('确认提交'),false);
	 assert.equal(resumeUploadAcknowledgementSignal('简历上传成功，请仔细核对简历信息！ 确定'),true);
	 assert.equal(resumeUploadAcknowledgementSignal('确认提交申请'),false);
 assert.equal(context.globalThis.CvMaxContentLogic.dialogStateFromText('当前职位投递要求：中文简历完整度达到100%。 创建完整简历'),'resume_prerequisite');
	 assert.equal(context.globalThis.CvMaxContentLogic.dialogStateFromText('上传新文件，请确认是否继续 取消 继续'),'unknown');
 assert.equal(context.globalThis.CvMaxContentLogic.dialogStateFromText('请登录',{hasPassword:true}),'login');
 assert.equal(context.globalThis.CvMaxContentLogic.boundedDialogText('  申请\n  职位  '),'申请 职位');
 assert.equal(context.globalThis.CvMaxContentLogic.finalSubmitSignal('提交申请'),true);
 assert.equal(context.globalThis.CvMaxContentLogic.finalSubmitSignal('立即申请'),false);
 assert.equal(context.globalThis.CvMaxContentLogic.workflowCanAdvance({surfaceKind:'resume_surface',formStage:'apply',controls:[{kind:'next',safe:true}]}),true);
 assert.equal(context.globalThis.CvMaxContentLogic.workflowCanAdvance({surfaceKind:'resume_surface',formStage:'apply',controls:[{kind:'next',safe:true},{kind:'next',safe:true}]}),false);
 assert.equal(context.globalThis.CvMaxContentLogic.workflowCanAdvance({surfaceKind:'entry_surface',formStage:'detail',controls:[{kind:'next',safe:true}]}),false);
 assert.equal(context.globalThis.CvMaxContentLogic.workflowCanAdvance({surfaceKind:'resume_surface',formStage:'apply',applicationFieldCount:1,requiredComplete:false,controls:[{kind:'next',safe:true}]}),false);
 const startA={textContent:'立即投递'},startB={textContent:' 立即投递 '},other={textContent:'查看已投'};
 assert.equal(context.globalThis.CvMaxContentLogic.equivalentStartControl([startA,startB],item=>item.textContent),startA);
 assert.equal(context.globalThis.CvMaxContentLogic.equivalentStartControl([startA,other],item=>item.textContent),null);
 const sectionElement={},heading=textContent=>({textContent,childNodes:[{nodeType:3,textContent}],children:[],contains:()=>false,compareDocumentPosition:()=>4});
 const questionAfterHeading=heading('是否有项目经验');questionAfterHeading.compareDocumentPosition=()=>4;
 sectionElement.ownerDocument={querySelectorAll:()=>[heading('项目经验'),questionAfterHeading]};
 const candidates=context.globalThis.CvMaxContentLogic.sectionCandidatesFor(sectionElement,String);
 assert.equal(candidates[0].key,'heading:是否有项目经验');
 assert.equal(candidates[1].key,'heading:项目经验');
 const nav={matches:()=>true,getAttribute:name=>name==='href'?'#program':null,textContent:'项目经历',contains:()=>false,compareDocumentPosition:()=>4,childNodes:[{nodeType:3,textContent:'项目经历'}]},sectionHeading=heading('项目经历 请填写以下信息'),fieldLabel=heading('工作描述'),otherAdd={ownerDocument:{querySelectorAll:()=>[nav,sectionHeading,fieldLabel]}};
 assert.equal(context.globalThis.CvMaxContentLogic.sectionCandidatesFor(otherAdd,String)[0].key,'heading:项目经历');
 assert.equal(context.globalThis.CvMaxContentLogic.outsideViewport({left:0,right:10,top:900,bottom:920},800,600),true);
 assert.equal(context.globalThis.CvMaxContentLogic.outsideViewport({left:0,right:10,top:100,bottom:120},800,600),false);
 assert.equal(JSON.stringify(context.globalThis.CvMaxContentLogic.sectionControlDescriptor({text:'教育经历',href:'#education',currentURL:'https://jobs.example/apply?x=1'})),JSON.stringify({sectionKey:'navigation:教育经历',label:'教育经历',target:'#education'}));
 assert.equal(JSON.stringify(context.globalThis.CvMaxContentLogic.sectionControlDescriptor({text:'基本信息',role:'tab',currentURL:'https://jobs.example/apply'})),JSON.stringify({sectionKey:'navigation:基本信息',label:'基本信息',target:null}));
 assert.equal(context.globalThis.CvMaxContentLogic.sectionControlDescriptor({text:'另一个岗位',href:'#/job/123',currentURL:'https://jobs.example/apply'}),null);
 assert.equal(context.globalThis.CvMaxContentLogic.sectionControlDescriptor({text:'教育经历',href:'https://evil.example/education',currentURL:'https://jobs.example/apply'}),null);
 assert.equal(context.globalThis.CvMaxContentLogic.sectionControlDescriptor({text:'立即投递',role:'button',currentURL:'https://jobs.example/apply'}),null);
 assert.match(content,/action\.kind==='section'/);
 assert.match(content,/\['add','next','start'\]/);
 assert.match(content,/contentRuntimeRevision=32/);
 assert.match(content,/sectionKey/);
 assert.match(content,/sectionCandidatesFor/);
 assert.match(content,/sectionCandidates/);
 assert.match(content,/isStartText\(element\)&&startVisible\(element\)/);
 const leaf={contains:()=>false},parent={contains:item=>item===leaf};
 assert.deepEqual(context.globalThis.CvMaxContentLogic.leafOptions([parent,leaf]),[leaf]);
 const box=(left,top)=>({contains:()=>false,getBoundingClientRect:()=>({left,top,width:10,height:10})}),anchor=box(0,0),near=box(5,5),far=box(100,100);
 assert.equal(context.globalThis.CvMaxContentLogic.nearestOption(anchor,[far,near]),near);
 assert.equal(context.globalThis.CvMaxContentLogic.nearestOption(anchor,[box(5,5),box(5,5)]),null);
 const visual={...box(5,5),getAttribute:()=>null},semantic={...box(5,5),getAttribute:name=>name==='role'?'option':null},hit={};semantic.contains=value=>value===hit;
 assert.equal(context.globalThis.CvMaxContentLogic.topmostOption({elementsFromPoint:()=>[hit]},[visual,semantic]),semantic);
 const overlay={contains:item=>item===semantic};
 assert.equal(context.globalThis.CvMaxContentLogic.topmostOption({elementsFromPoint:()=>[overlay]},[visual,semantic]),semantic);
 assert.equal(context.globalThis.CvMaxContentLogic.equivalentOption([visual,semantic]),semantic);
 const option=text=>({textContent:text});
 assert.equal(context.globalThis.CvMaxContentLogic.matchingOptions([option('全日制'),option('非全日制')],'统招全日制',String).matchedValue,'全日制');
 assert.equal(context.globalThis.CvMaxContentLogic.matchingOptions([option('本科'),option('本科生')],'本科',String).normalized,false);
 assert.match(content,/input,select,textarea,\[role="combobox"\]/);
 assert.match(content,/const observable=element=>visible\(element\)&&!element\.closest\('\[aria-hidden="true"\],\[inert\]'\)/);
 assert.match(content,/function errors\(scope=document\)\{const conventional=[^\n]+\.filter\(element=>observable\(element\)/);
 assert.match(content,/NodeFilter\.SHOW_TEXT\),pattern=\/\(\?:开始\|结束/);
 assert.match(content,/scopeInputs=descendants\(scope,'input,select,textarea'\)\.filter\(observable\)/);
 assert.match(evidence,/if\(r\.bottom<=0\|\|r\.top>=innerHeight\|\|r\.right<=0\|\|r\.left>=innerWidth\)return r\.width>0&&r\.height>0/);
 assert.match(content,/aria-controls/);
 assert.match(content,/ud__select__selector/);
 assert.match(content,/ud__select__option/);
 assert.match(content,/structuredMatch/);
 assert.match(content,/related\(clean\(item\.textContent\)\)&&actionable/);
 assert.match(content,/site_selection_not_retained/);
 assert.match(content,/protectedValue=action.kind==='select'\?fieldValue\(element\):element.value/);
 assert.match(content,/typeof element.checkValidity!=='function'/);
 assert.match(content,/dropdown__item/);
 assert.match(content,/!root\.contains\(item\)/);
 assert.match(content,/elementFromPoint/);
 assert.match(content,/tokens\.includes\('ud__select__list__item'\)/);
 assert.match(content,/ud__select__selector__selectItem/);
 assert.match(content,/scrollIntoView/);
 assert.match(content,/function activateControl/);
 assert.match(content,/new PointerEvent\('pointerdown'/);
 assert.match(content,/new PointerEvent\('pointerup'/);
 assert.match(content,/new MouseEvent\('mousedown'/);
 assert.match(content,/target\.click\(\)/);
 assert.match(content,/visibleChoices/);
 assert.match(content,/rawChoices/);
 assert.match(content,/rawMatch/);
 assert.match(content,/function choiceGroup/);
 assert.match(content,/requiredFieldComplete/);
 assert.match(content,/nativeResumeParse/);
 assert.match(content,/native_parser_triggered_requires_new_observation/);
 assert.match(content,/native_parser_automatic_upload_requires_new_observation/);
 assert.match(content,/const nativeParse=action\.kind==='native_parse'\?nativeParseContext\(element\):null/);
 assert.match(content,/reuseUploaded/);
 assert.match(content,/root\.querySelectorAll\('\*'\)/);
 assert.match(content,/__cvmaxContentVersion/);
 assert.match(content,/removeListener/);
 assert.match(content,/attachShadow/);
 assert.match(content,/实时执行进度/);
 assert.match(content,/target-frame/);
 assert.match(content,/class="connector"/);
 assert.match(content,/正在处理：/);
 assert.match(background,/CvMax 已打开申请页/);
 assert.match(background,/applicationStartObserved/);
	 assert.match(background,/function activateInMainWorld/);
	 assert.match(background,/CvMaxEvidence\.resolveInteraction\(surface,expected\)/);
	 assert.match(content,/CvMaxEvidence\.interactionCandidates\(scope\)/);
	 assert.match(content,/CvMaxEvidence\.interactionIdentity\(element\)/);
	 assert.match(content,/CvMaxEvidence\.actionable\(element,scope\)/);
	 assert.doesNotMatch(background,/surface\.querySelectorAll\('button,input\[type="button"\]/);
	 assert.match(background,/surfaces\.flatMap/);
	 assert.match(background,/\['activate','start'\]\.includes/);
	 assert.match(content,/application_start_validated/);
	 assert.match(background,/candidates\.length!==1/);
	 assert.doesNotMatch(background,/leafDialogs\.length !== 1/);
	 assert.match(background,/world: 'MAIN'/);
	 assert.match(background,/HTMLElement\.prototype\.click\.call/);
	 assert.match(background,/main_world_pointer/);
	 assert.match(background,/main_world_anchor_invalid/);
	 assert.doesNotMatch(background,/fillInMainWorld|data-cvmax-action-token|main_world_started/);
	 assert.match(content,/function interactions\(/);
	 assert.match(content,/action\.kind==='activate'/);
	 assert.doesNotMatch(background,/简历上传成功|resumeUploadSuccess|顺丰|字节/);
 assert.match(background,/installWindowOpenCapture/);
 assert.match(background,/__cvmaxEarlyOpenCapture/);
 assert.match(background,/captureStartedAt - 30_000/);
 assert.match(background,/opened = \[await waitForLoad\(created\.id, message\.expiresAt\)\]/);
 assert.match(background,/application_start_captured_ambiguous_urls/);
 assert.match(background,/knownTabIds/);
 assert.match(background,/openedNewTab/);
 assert.match(background,/captureVisibleTab/);
 assert.match(background,/chrome\.tabs\.update\(tab\.id, \{active: true\}\)/);
 assert.match(background,/chrome\.tabs\.update\(previous\.id, \{active: true\}\)/);
 assert.match(background,/scope: 'private_task'/);
 assert.match(content,/role="progressbar"/);
 assert.match(content,/CvMax 自动流程/);
 assert.match(content,/接下来由你完成/);
 assert.match(content,/\.terminal \.runtime\{display:none\}/);
 assert.match(content,/下一步：检查剩余问题并手动提交/);
 assert.match(content,/aria-current/);
 assert.match(content,/progress\.workflow\.steps/);
 assert.match(content,/pageEmergencyStop/);
 assert.match(content,/application_start_not_safe/);
 assert.match(content,/prerequisites\.length===1\?prerequisites\[0\]/);
 assert.match(content,/function activeDialog\(\)/);
 assert.match(content,/discoveredFields=fields\(scope\)/);
 assert.match(content,/filePurpose:filePurpose\(element,text\)/);
 assert.match(content,/currentFields=surfaceKind==='resume_surface'&&formStage==='apply'\?discoveredFields:\[\]/);
 assert.match(content,/surfaceKind=pageSurfaceFrom/);
 assert.match(content,/hasApplicationEntry/);
 assert.match(content,/hasResumeEntry/);
 assert.match(content,/hasResumeForm/);
 assert.match(content,/current\.applicationFieldCount/);
 assert.match(content,/allElements=descendants\(scope,'\*'\)/);
 assert.match(content,/textStarts=allElements\.filter/);
 assert.match(content,/applicationStartSignal\(textOf\(element\)\)/);
 assert.match(content,/observedControl\?\.kind!==action\.kind/);
 // Dialog discovery moved to the shared evidence primitive; behavior is covered by browser-evidence.test.mjs.
 assert.match(content,/CvMaxEvidence\.activeSurface/);
 assert.match(content,/elementsFromPoint/);
 assert.match(content,/activeDialog:dialog\?/);
 assert.match(content,/只填写和核验，不会提交/);
 assert.match(background,/sender\.tab\.id === state\.active\?\.tabId/);
 assert.match(background,/sender\.url === state\.active\?\.targetURL/);
 assert.match(content,/element\.checked===desiredChecked\(action\.value\)/);
 for(const file of [manifest.background.service_worker,manifest.action.default_popup,'content.js','content-logic.js','protocol.js'])assert.equal(fs.existsSync(path.join(dir,file)),true,file);
});

test('application start waits for a same-URL form, prerequisite modal, or login transition',()=>{
 const before={url:'https://jobs.example/detail/1',documentEpoch:'doc-1',fieldCount:0,pageState:'normal'};
 assert.equal(applicationStartObserved(before,{url:before.url,documentEpoch:'doc-1',fields:[],formStage:'detail',loginRequired:false}),false);
 assert.equal(applicationStartObserved(before,{url:before.url,documentEpoch:'doc-1',fields:[],formStage:'detail',pageState:'resume_prerequisite',loginRequired:false}),true);
 assert.equal(applicationStartObserved({...before,pageState:'resume_prerequisite'},{url:before.url,documentEpoch:'doc-1',fields:[],formStage:'detail',pageState:'normal',loginRequired:false}),false);
 assert.equal(applicationStartObserved({...before,pageState:'resume_prerequisite'},{url:before.url,documentEpoch:'doc-2',fields:[],formStage:'detail',pageState:'normal',loginRequired:false}),false);
 assert.equal(applicationStartObserved(before,{url:before.url,documentEpoch:'doc-1',fields:[{}],formStage:'apply',loginRequired:false}),true);
 assert.equal(applicationStartObserved(before,{url:before.url,documentEpoch:'doc-1',fields:[],formStage:'apply',loginRequired:true}),true);
 assert.equal(applicationStartObserved(before,{url:'https://jobs.example/apply/1',documentEpoch:'doc-1',fields:[],formStage:'unknown',loginRequired:false}),true);
});

test('a resume prerequisite requires durable navigation or a real form before capture is restored',()=>{
 const before={url:'https://jobs.example/detail/1',documentEpoch:'doc-1',fieldCount:0,pageState:'resume_prerequisite'};
 assert.equal(applicationStartSettled(before,{url:before.url,documentEpoch:'doc-2',fields:[],formStage:'detail',pageState:'normal',loginRequired:true},{originalTabId:1,settledTabId:1}),false);
 assert.equal(applicationStartSettled(before,{url:before.url,documentEpoch:'doc-1',fields:[{}],formStage:'apply',pageState:'normal',loginRequired:false},{originalTabId:1,settledTabId:1}),true);
 assert.equal(applicationStartSettled(before,{url:before.url,documentEpoch:'doc-1',fields:[],formStage:'detail',pageState:'normal',loginRequired:false},{originalTabId:1,settledTabId:2}),true);
});

test('bridge endpoint is loopback-only and token is bounded',()=>{
 assert.equal(normalizeEndpoint('ws://localhost:18833'),'ws://localhost:18833/');assert.equal(validateToken('CV-4821'),'CV-4821');
 for(const value of ['wss://example.com','ws://example.com:18833','ws://user@127.0.0.1:18833','ws://127.0.0.1:18833/other'])assert.throws(()=>normalizeEndpoint(value));
 for(const value of ['', 'short', 'has space'])assert.throws(()=>validateToken(value));
 assert.equal(normalizeOrigin('https://jobs.example/apply'),'https://jobs.example');assert.throws(()=>normalizeOrigin('chrome://extensions'));
});

test('browser family detection distinguishes Edge from Chrome before pairing',()=>{
 assert.equal(detectBrowserFamily('Mozilla/5.0 Chrome/140.0 Safari/537.36 Edg/140.0'),'edge');
 assert.equal(detectBrowserFamily('Mozilla/5.0 Chrome/140.0 Safari/537.36'),'chrome');
 assert.equal(detectBrowserFamily('',[{brand:'Microsoft Edge',version:'140'}]),'edge');
 assert.equal(detectBrowserFamily('custom browser'),'unknown');
});

test('application starts may continue across subdomains of one recruitment site',()=>{
 assert.equal(normalizeSiteBoundary('https://campus.pingan.com/positionDetail'),'https://pingan.com');
 assert.equal(normalizeSiteBoundary('https://talent.pingan.com/recruit/login.html'),'https://pingan.com');
 assert.notEqual(normalizeSiteBoundary('https://talent.pingan.com/recruit/login.html'),normalizeSiteBoundary('https://accounts.example.com/login'));
});

test('commands require an authorized exact tab, URL, lease and live run',()=>{
 const now=1000,tab={id:7,url:'https://jobs.example/apply'},base={kind:'command',id:'one',taskId:'task-1',tabId:7,targetURL:tab.url,protocol:EXTENSION_PROTOCOL,expiresAt:2000,action:'act',runId:'run-1'};
 assert.equal(validateBridgeCommand(base,{tab,blockedRuns:new Set(),now}).origin,'https://jobs.example');
 for(const changed of [{tabId:8},{targetURL:'https://jobs.example/other'},{expiresAt:999},{expiresAt:12000},{action:'submit'},{runId:''}])assert.throws(()=>validateBridgeCommand({...base,...changed},{tab,blockedRuns:new Set(),now}));
 assert.equal(validateBridgeCommand({...base,action:'refresh',expiresAt:9000},{tab,blockedRuns:new Set(),now}).origin,'https://jobs.example');
 assert.equal(validateBridgeCommand({...base,action:'screenshot'},{tab,blockedRuns:new Set(),now}).origin,'https://jobs.example');
 assert.throws(()=>validateBridgeCommand(base,{tab,blockedRuns:new Set(['run-1']),now}));
 assert.equal(validateBridgeCommand({...base,expiresAt:12000,actionSpec:{kind:'start'}},{tab,blockedRuns:new Set(),now}).origin,'https://jobs.example');
 assert.equal(validateBridgeCommand({...base,expiresAt:30000,actionSpec:{kind:'start'}},{tab,blockedRuns:new Set(),now}).origin,'https://jobs.example');
 assert.throws(()=>validateBridgeCommand({...base,expiresAt:32000,actionSpec:{kind:'start'}},{tab,blockedRuns:new Set(),now}));
});

test('a verified application entry rebinds one safe control after framework rerender',()=>{
 const content=fs.readFileSync(path.join(root,'../extension/content.js'),'utf8');
 assert.match(content,/action\.kind==='start'&&action\.entryAnchor\?\.label/);
 assert.match(content,/control\.kind==='start'&&control\.safe/);
 assert.match(content,/if\(matches\.length===1\)element=matches\[0\]/);
});

test('progress projection is bounded, value-free and accepted as a bridge action',()=>{
 const workflow={version:1,path:'direct',current:'fill',steps:[{id:'open',label:'打开申请页',status:'done'},{id:'fill',label:'填写简历事实',status:'current'}]};
 const progress=normalizeProgress({taskId:'task-1',revision:4,phase:'filling',title:'正在填写资料',detail:'只写入有来源的字段',fieldLabel:'姓名',sectionLabel:'基本信息',targetRef:'f3',current:2,total:5,verified:1,nextOwner:'CvMax',lastConfirmed:'手机号码',workflow,terminal:false,finalSubmitAllowed:true});
 assert.deepEqual(progress,{taskId:'task-1',revision:4,phase:'filling',title:'正在填写资料',detail:'只写入有来源的字段',fieldLabel:'姓名',sectionLabel:'基本信息',targetRef:'f3',current:2,total:5,verified:1,nextOwner:'CvMax',lastConfirmed:'手机号码',workflow,terminal:false,finalSubmitAllowed:false});
 const now=1000,tab={id:7,url:'https://jobs.example/apply'},command={kind:'command',id:'progress-one',action:'progress',taskId:'task-1',tabId:7,targetURL:tab.url,runId:'run-1',protocol:EXTENSION_PROTOCOL,expiresAt:2000,progress};
 assert.equal(validateBridgeCommand(command,{tab,blockedRuns:new Set(),now}).origin,'https://jobs.example');
 for(const changed of [{progress:{...progress,phase:'invented'}},{progress:{...progress,current:6}},{progress:{...progress,nextOwner:'third-party'}},{progress:{...progress,fieldLabel:'x'.repeat(101)}},{progress:{...progress,sectionLabel:'x'.repeat(81)}},{progress:{...progress,targetRef:'x'.repeat(101)}},{progress:{...progress,workflow:{...workflow,current:'missing'}}},{progress:{...progress,workflow:{...workflow,steps:[...workflow.steps,{id:'fill',label:'重复',status:'pending'}]}}}])assert.throws(()=>validateBridgeCommand({...command,...changed},{tab,blockedRuns:new Set(),now}));
});

test('open command accepts one fresh http target without a pre-existing tab',()=>{
 const now=1000,command={kind:'command',id:'open-one',action:'open',taskId:'task-one',runId:'run-one',protocol:EXTENSION_PROTOCOL,targetURL:'https://jobs.example/apply',expiresAt:20000};
 assert.equal(validateOpenCommand(command,now).origin,'https://jobs.example');
 for(const changed of [{taskId:''},{runId:''},{targetURL:'chrome://extensions'},{expiresAt:999},{expiresAt:40000},{action:'act'}])assert.throws(()=>validateOpenCommand({...command,...changed},now));
});
test('current command resolves the active tab without page-side interaction',()=>{assert.equal(validateCurrentCommand({kind:'command',id:'current-one',action:'current',protocol:EXTENSION_PROTOCOL,expiresAt:2000},1000),true);assert.throws(()=>validateCurrentCommand({kind:'command',id:'bad',action:'current',protocol:EXTENSION_PROTOCOL,expiresAt:12000},1000));assert.throws(()=>validateCurrentCommand({kind:'command',id:'old',action:'current',protocol:{current:1,minimum:1},expiresAt:2000},1000),/protocol_extension_incompatible/)});
