import {publicCandidateKey} from '../src/page-model.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {generateKeyPairSync} from 'node:crypto';
import {RecipeRegistryClient} from '../src/recipe-registry-client.mjs';import {RecipeRegistryApp} from '../src/recipe-registry-app.mjs';import {recordVerifiedTransition,markRecipeTerminal} from '../src/recipe.mjs';import {signRecipeRelease} from '../src/recipe-release.mjs';
const snap=value=>({url:'https://jobs.example.test/apply',formStage:'apply',pageState:'normal',fields:[{ref:'name',label:'姓名',semanticId:'name',type:'text',value}],controls:[],interactions:[]});
const candidate=()=>{const recipes={};recordVerifiedTransition(recipes,{sourceSnapshot:snap(''),targetSnapshot:snap('姓名'),runId:'local',actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});return markRecipeTerminal(recipes,snap('姓名'),{predecessorKind:'fill',coverageFactIds:['name']})};
function repository(){const releases=new Map(),feedback=[];let next=1;return{feedback,async saveCandidate(bundle){const found=[...releases].find(([,item])=>JSON.stringify(item.bundle)===JSON.stringify(bundle));if(found)return{releaseId:found[0],releaseVersion:found[0],status:found[1].status};const id=next++;releases.set(id,{bundle,status:'candidate'});return{releaseId:id,releaseVersion:id,status:'candidate'}},async recordFeedback(value){feedback.push(value);return{accepted:true}},async releaseStats(id){const item=releases.get(id);return item&&{status:item.status,independentInstallations:new Set(feedback.filter(x=>x.releaseId===id).map(x=>x.installationHash)).size,verifiedRuns:feedback.filter(x=>x.releaseId===id&&x.outcome==='verified').length,failedRuns:0}},async updateReleaseStats(){},async setReleaseStatus(id,status){releases.get(id).status=status},async releasedBundles(){return[]},async releaseBundle(id){return releases.get(id).bundle},async publishRelease(id,bundle,signed){Object.assign(releases.get(id),{status:'released',bundle,signed})},async releasedRecord(){return null}}}

test('independent installations promote a complete recipe release',async()=>{const keys=generateKeyPairSync('ed25519'),repo=repository(),app=new RecipeRegistryApp({repository:repo,privateKey:keys.privateKey,signingKeyId:'key',installationPepper:'pepper',policy:{canaryInstallations:1,releaseInstallations:2,suspendFailures:2,maximumFailureRate:.1}}),bundle=candidate();for(const transition of Object.values(bundle.transitions))transition.verification={counterexamplePassed:true,independentVariants:2,prelearnRuns:2,version:3,effect:'retained_values',anchorRebound:true,replayCount:1};const one=await app.candidate({installationId:'installation-0001',bundle,evidenceDigest:'a'.repeat(64),receiptId:'one'});assert.equal(one.status,'canary');const two=await app.candidate({installationId:'installation-0002',bundle,evidenceDigest:'b'.repeat(64),receiptId:'two'});assert.equal(two.status,'released')});

test('a signed recipe and page model are cached without a plugin update',async()=>{const keys=generateKeyPairSync('ed25519'),bundle=candidate();bundle.pageModel={formatVersion:1,mappings:{[publicCandidateKey('heading:教育背景')]:'教育经历'}};const signed={...signRecipeRelease(bundle,keys.privateKey,'key'),status:'released',releaseId:1,releaseVersion:1,bundle},dir=fs.mkdtempSync(path.join(os.tmpdir(),'cvmax-recipe-cache-'));try{const client=new RecipeRegistryClient({baseUrl:'https://registry.test',installationId:'installation-cache',publicKeys:{key:keys.publicKey},cacheFile:path.join(dir,'cache.json'),fetchImpl:async()=>new Response(JSON.stringify(signed),{status:200})});const release=await client.getReleased(bundle.system.key);assert.equal(release.bundle.recipeId,bundle.recipeId);assert.equal(release.bundle.pageModel.mappings[publicCandidateKey('heading:教育背景')],'教育经历');assert.equal(client.cachedBundles()[bundle.system.key].pageModel.mappings[publicCandidateKey('heading:教育背景')],'教育经历')}finally{fs.rmSync(dir,{recursive:true,force:true})}});

test('offline candidate writes are queued without private values',async()=>{const keys=generateKeyPairSync('ed25519'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'cvmax-recipe-queue-'));try{const client=new RecipeRegistryClient({baseUrl:'https://registry.test',writeToken:'token',installationId:'installation-queue',publicKeys:{key:keys.publicKey},cacheFile:path.join(dir,'cache.json'),fetchImpl:async()=>{throw Error('offline')}}),result=await client.submitCandidate({bundle:candidate(),evidenceDigest:'c'.repeat(64),receiptId:'one'});assert.equal(result.queued,true);const saved=fs.readFileSync(path.join(dir,'cache.json'),'utf8');assert.equal(saved.includes('姓名'),false);assert.equal(saved.includes('local'),false)}finally{fs.rmSync(dir,{recursive:true,force:true})}});

test('installation counts cannot publish an unverified learning candidate',async()=>{
 const keys=generateKeyPairSync('ed25519'),repo=repository(),app=new RecipeRegistryApp({repository:repo,privateKey:keys.privateKey,signingKeyId:'key',installationPepper:'pepper',policy:{canaryInstallations:1,releaseInstallations:2,suspendFailures:2,maximumFailureRate:.1}});
 for(const installationId of ['installation-one','installation-two']){
 const result=await app.candidate({installationId,bundle:candidate(),evidenceDigest:'a'.repeat(64),receiptId:installationId});
 assert.notEqual(result.status,'released');assert.notEqual(result.status,'canary');
 }
});

test('withdrawn releases are removed from durable cache without a plugin update',async()=>{
 const keys=generateKeyPairSync('ed25519'),bundle=candidate(),signed={...signRecipeRelease(bundle,keys.privateKey,'key'),status:'released',releaseId:1,releaseVersion:1,bundle},dir=fs.mkdtempSync(path.join(os.tmpdir(),'cvmax-withdraw-'));let retired=false;
 try{const config={baseUrl:'https://registry.test',installationId:'installation-withdraw',publicKeys:{key:keys.publicKey},cacheFile:path.join(dir,'cache.json'),fetchImpl:async()=>retired?new Response('',{status:404}):new Response(JSON.stringify(signed))};const client=new RecipeRegistryClient(config);await client.getReleased(bundle.system.key);assert.ok(client.cachedBundles()[bundle.system.key]);retired=true;assert.equal(await client.getReleased(bundle.system.key),null);assert.equal(new RecipeRegistryClient(config).cachedBundles()[bundle.system.key],undefined)}finally{fs.rmSync(dir,{recursive:true,force:true})}
});
