import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import{CvMaxService}from'../src/service.mjs';import{recordVerifiedExperience}from'../src/experience.mjs';
function fixture(fn){return async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cvmax-service-'));const snapshot={url:'https://example.test/apply',documentEpoch:'doc1',fingerprint:'page1',fields:[{ref:'name',label:'姓名',semanticId:'name',value:'',type:'text'}],controls:[],canAdvance:false,completionVerifiable:false};let calls=[],requests=[];let browser=async(action,a)=>{calls.push(action);requests.push({action,args:structuredClone(a)});if(action==='observe')return structuredClone(snapshot);if(action==='act'){snapshot.fields[0].value=a.actionSpec.value;return{accepted:true}}return{stopped:true}};const config={file:path.join(dir,'state.json'),browser:(...a)=>browser(...a),attachments:{read(){return{filename:'resume.pdf',mime:'application/pdf',sha256:'a'.repeat(64),bytes:Buffer.from('resume')}},persistResume(_ref,id,revision){return{resource:`saved:${id}/${revision}.pdf`,sha256:'a'.repeat(64),size:6,mime:'application/pdf',scope:'resume'}}},allowedOrigins:['https://example.test']};let service=new CvMaxService(config);try{await fn({get service(){return service},restart(){service=new CvMaxService(config)},snapshot,calls,requests,setBrowser(fn){browser=fn}})}finally{fs.rmSync(dir,{recursive:true,force:true})}}}
const create=s=>s.create({clientRequestId:'one',targets:[{url:'https://example.test/apply',tabId:1}],facts:[{id:'name',value:'Synthetic Applicant',sourceRef:'synthetic:test'}]});
async function ready(s){let t=create(s);t=s.claim({taskId:t.taskId,expectedRevision:t.revision});return(await s.observe({taskId:t.taskId})).task}
const wait=()=>new Promise(r=>setTimeout(r,20));
test('configured services consume only public releases and upload value-free feedback',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cvmax-public-')),snapshot={url:'https://example.test/apply',documentEpoch:'doc-public',fields:[{ref:'name',label:'姓名',semanticId:'name',value:'',type:'text'}],controls:[],canAdvance:false,completionVerifiable:false},experiences={},training={snapshot:{...structuredClone(snapshot),fields:[{...snapshot.fields[0],value:'Training'}]},evidence:[{action:{kind:'fill',fieldRef:'name',semanticId:'name',semanticOrdinal:0,factId:'name',value:'Training'}}]};training.runId='one';recordVerifiedExperience(experiences,training,()=>true,['Training']);training.runId='two';recordVerifiedExperience(experiences,training,()=>true,['Training']);const bundle=Object.values(experiences)[0],candidates=[],feedback=[],registry={cachedBundles(){return{}},async getReleased(){return{releaseId:9,releaseVersion:1,status:'released',bundle}},async submitCandidate(value){candidates.push(value);return{status:'candidate'}},async submitFeedback(value){feedback.push(value);return{status:'released'}}};let browser=async(action,args)=>{if(action==='observe')return structuredClone(snapshot);if(action==='act'){snapshot.fields[0].value=args.actionSpec.value;return{accepted:true}}return{stopped:true}};try{const service=new CvMaxService({file:path.join(dir,'state.json'),browser,attachments:{read(){throw Error('unused')}},allowedOrigins:['https://example.test'],experienceRegistry:registry});let t=service.create({clientRequestId:'public-release',targets:[{url:snapshot.url,tabId:1}],facts:[{id:'name',value:'Private Applicant',sourceRef:'file:resume.pdf#page=1'}]});t=service.claim({taskId:t.taskId,expectedRevision:t.revision});let observed=await service.observe({taskId:t.taskId});assert.equal(observed.experience.releaseId,9);assert.equal(observed.experience.suggestedActions.length,1);await service.apply({taskId:t.taskId,expectedRevision:observed.task.revision,actions:observed.experience.suggestedActions});await wait();observed=await service.observe({taskId:t.taskId});service.finish({taskId:t.taskId,expectedRevision:observed.task.revision,outcome:'partial'});await service.drainRegistry();assert.equal(candidates.length,0);assert.equal(feedback.length,1);assert.equal(feedback[0].outcome,'verified');assert.equal(JSON.stringify(feedback).includes('Private Applicant'),false);assert.equal(service.health().publicExperience,'configured')}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('version 3 partial task evidence is backfilled once into field experience',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cvmax-migrate-')),file=path.join(dir,'state.json'),makeTask=(id,runId,value)=>({taskId:id,state:'finished',current:1,factSnapshot:{facts:[{id:'name',value,sourceRef:'synthetic:test'}]},applications:[{runId,outcome:'partial',snapshot:{url:`https://example.test/jobs/${id}/apply`,fields:[{ref:'name',label:'姓名',semanticId:'name',type:'text',value}],controls:[]},evidence:[{action:{kind:'fill',fieldRef:'name',semanticId:'name',semanticOrdinal:0,factId:'name',value},evidence:{accepted:true}}]}]});fs.writeFileSync(file,JSON.stringify({version:3,tasks:{one:makeTask('11111','run-one','First Private'),two:makeTask('22222','run-two','Second Private')},requests:{},experiences:{}}));try{const config={file,browser:async()=>({}),attachments:{read(){throw Error('unused')}},allowedOrigins:['https://example.test']};let service=new CvMaxService(config),stored=Object.values(service.store.data.experiences)[0];assert.equal(service.store.data.version,7);assert.equal(stored.status,'reusable');assert.equal(JSON.stringify(stored).includes('Private'),false);const before=JSON.stringify(stored);service=new CvMaxService(config);stored=Object.values(service.store.data.experiences)[0];assert.equal(JSON.stringify(stored),before)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('health reports service and browser readiness without exposing a submit capability',fixture(async f=>{assert.deepEqual(f.service.health(),{service:'ready',browser:'disconnected',finalSubmitAllowed:false})}));
test('a staged client request hides fact values and create freezes it without agent retransmission',fixture(async f=>{const saved=f.service.request_save({clientRequestId:'staged-one',links:['https://example.test/apply'],facts:[{id:'name',value:'Private Applicant',sourceRef:'file:resume.pdf#page=1'}],attachment:{resource:'test',sha256:'a'.repeat(64),size:6,mime:'application/pdf'}});assert.deepEqual(saved.links,['https://example.test/apply']);assert.equal(saved.factCount,1);assert.equal(saved.hasAttachment,true);assert.equal(JSON.stringify(saved).includes('Private Applicant'),false);assert.equal(JSON.stringify(f.service.request_get({clientRequestId:'staged-one'})).includes('Private Applicant'),false);const target={url:'https://example.test/apply',tabId:1},task=f.service.create({clientRequestId:'staged-one',targets:[target]});assert.equal(f.service.task_context({taskId:task.taskId}).facts[0].value,'Private Applicant');assert.equal(task.factSnapshot.factCount,1);assert.throws(()=>f.service.create({clientRequestId:'staged-one',targets:[target],facts:[{id:'name',value:'Other',sourceRef:'user:answer'}]}),/staged_request_scope_conflict/)}));
test('staged request idempotency uses attachment identity instead of a temporary resource path',fixture(async f=>{const base={clientRequestId:'staged-retry',currentPage:true,facts:[],attachment:{resource:'test',sha256:'a'.repeat(64),size:6,mime:'application/pdf',expiresAt:1}},first=f.service.request_save(base),second=f.service.request_save({...base,attachment:{...base.attachment,resource:'another-temporary-path',expiresAt:2}});assert.deepEqual(second,first);assert.throws(()=>f.service.request_save({...base,facts:[{id:'city',value:'Beijing',sourceRef:'user:answer'}]}),/request_key_conflict/)}));
test('each saved resume is one isolated fact aggregate and tasks never borrow from another resume',fixture(async f=>{const attachment={resource:'test'},a=f.service.resume_save({saveRequestId:'save-a',name:'数据分析版',facts:[{id:'name',value:'Applicant A',sourceRef:'file:resume-a.pdf#page=1'}],attachment}),b=f.service.resume_save({saveRequestId:'save-b',name:'产品经理版',facts:[{id:'name',value:'Applicant B',sourceRef:'file:resume-b.pdf#page=1'},{id:'email',value:'b@example.test',sourceRef:'file:resume-b.pdf#page=1'}],attachment});const ta=f.service.create({clientRequestId:'resume-a-task',targets:[{url:'https://example.test/apply',tabId:1}],resume:{id:a.resumeId,revision:a.revision}}),tb=f.service.create({clientRequestId:'resume-b-task',targets:[{url:'https://example.test/apply',tabId:2}],resume:{id:b.resumeId,revision:b.revision}}),ca=f.service.task_context({taskId:ta.taskId}),cb=f.service.task_context({taskId:tb.taskId});assert.deepEqual(ca.facts.map(x=>[x.id,x.value]),[['name','Applicant A']]);assert.deepEqual(cb.facts.map(x=>[x.id,x.value]),[['name','Applicant B'],['email','b@example.test']]);assert.deepEqual(ta.factSnapshot.resumeFact,{id:a.resumeId,revision:1,name:'数据分析版'});assert.equal(JSON.stringify(f.service.resume_list()).includes('Applicant'),false)}));
test('a task freezes the selected resume revision while a later revision serves only new tasks',fixture(async f=>{const attachment={resource:'test'},v1=f.service.resume_save({saveRequestId:'save-v1',name:'技术版',facts:[{id:'name',value:'Version One',sourceRef:'file:resume.pdf#page=1'}],attachment}),oldTask=f.service.create({clientRequestId:'old-revision-task',targets:[{url:'https://example.test/apply',tabId:1}],resume:{id:v1.resumeId,revision:1}}),v2=f.service.resume_save({saveRequestId:'save-v2',resumeId:v1.resumeId,expectedRevision:1,name:'技术版',facts:[{id:'name',value:'Version Two',sourceRef:'user:resume-correction'}]}),newTask=f.service.create({clientRequestId:'new-revision-task',targets:[{url:'https://example.test/apply',tabId:2}],resume:{id:v2.resumeId,revision:2}});assert.equal(f.service.task_context({taskId:oldTask.taskId}).facts[0].value,'Version One');assert.equal(f.service.task_context({taskId:newTask.taskId}).facts[0].value,'Version Two');assert.throws(()=>f.service.create({clientRequestId:'stale-revision-task',targets:[{url:'https://example.test/apply',tabId:3}],resume:{id:v1.resumeId,revision:1}}),/revision_conflict/)}));
test('public task views and reports omit fact values and internal action values',fixture(async f=>{let t=await ready(f.service);await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();t=(await f.service.observe({taskId:t.taskId})).task;const view=f.service.status({taskId:t.taskId}),report=f.service.report({taskId:t.taskId});assert.deepEqual(view.factSnapshot,{id:f.service.get(t.taskId).factSnapshot.id,factCount:1,hasAttachment:false});assert.equal(JSON.stringify(view).includes('Synthetic Applicant'),false);assert.equal(JSON.stringify(report).includes('Synthetic Applicant'),false);assert.equal('strategies'in view.applications[0].budget,false);assert.deepEqual(report.history[0].evidence[0],{operationId:f.service.get(t.taskId).applications[0].operation.id,kind:'fill',fieldRef:'name',factId:'name',verified:true});const context=f.service.task_context({taskId:t.taskId});assert.equal(context.facts[0].value,'Synthetic Applicant')}));
test('service projects real field and section progress without exposing fact values',fixture(async f=>{let t=create(f.service);t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;const observing=f.requests.find(item=>item.action==='observe').args.progress;assert.equal(observing.phase,'observing');assert.equal(observing.fieldLabel,'检查页面字段');await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();const acting=f.requests.find(item=>item.action==='act').args.progress;assert.equal(acting.phase,'filling');assert.equal(acting.fieldLabel,'姓名');assert.equal(acting.sectionLabel,'基本信息');assert.equal(acting.targetRef,'name');assert.equal(acting.current,1);assert.equal(acting.total,1);assert.equal(JSON.stringify(acting).includes('Synthetic Applicant'),false);const projected=f.requests.filter(item=>item.action==='progress').at(-1).args.progress;assert.equal(projected.phase,'verifying');assert.equal(projected.verified,1);assert.equal(projected.lastConfirmed,'姓名');assert.equal(projected.finalSubmitAllowed,false)}));
test('service opens an authorized link through the browser and returns the bound tab',fixture(async f=>{f.setBrowser(async(action,args)=>{assert.equal(action,'open');return{tabId:7,url:args.targetURL,requestedURL:args.targetURL}});assert.deepEqual(await f.service.open({url:'https://example.test/apply'}),{tabId:7,url:'https://example.test/apply',requestedURL:'https://example.test/apply'});await assert.rejects(f.service.open({url:'https://outside.test/apply'}),/authorized/)}));
test('service resolves the current recruitment tab through the browser',fixture(async f=>{f.setBrowser(async action=>{assert.equal(action,'current');return{tabId:8,url:'https://example.test/apply'}});assert.deepEqual(await f.service.current(),{tabId:8,url:'https://example.test/apply'})}));
test('authoritative result requires fresh page verification; submit cannot be planned',fixture(async f=>{let t=await ready(f.service);assert.throws(()=>f.service.finish({taskId:t.taskId,expectedRevision:t.revision,outcome:'ready_for_review'}),/completion/);await assert.rejects(f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'submit'}]}),/forbidden/);t=f.service.status({taskId:t.taskId});await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();t=f.service.status({taskId:t.taskId});assert.equal(t.applications[0].operation.state,'verified');f.snapshot.canAdvance=true;f.snapshot.completionVerifiable=true;t=(await f.service.observe({taskId:t.taskId})).task;t=f.service.finish({taskId:t.taskId,expectedRevision:t.revision,outcome:'ready_for_review'});assert.equal(t.state,'finished');assert.equal(t.applications[0].outcome,'ready_for_review');assert.equal(f.calls.filter(c=>c==='act').length,1)}));
test('fresh observation revokes an action receipt when the page did not retain the value',fixture(async f=>{let t=await ready(f.service);await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();f.snapshot.fields[0].value='';t=(await f.service.observe({taskId:t.taskId})).task;assert.equal(t.state,'needs_attention');assert.equal(t.applications[0].operation.state,'unknown')}));
test('attachment verification follows a replacement input by semantic id and visible filename',fixture(async f=>{const snapshot={fields:[{ref:'replacement',semanticId:'resume',value:'',receiptText:'resume.pdf 上次上传'}],attachmentReceipt:[]};assert.equal(f.service.actionVerified(snapshot,{kind:'upload',fieldRef:'old',semanticId:'resume',filename:'resume.pdf'}),true)}));
test('native resume parsing is preferred, verified by page change, and its values can be corrected',fixture(async f=>{f.snapshot.fields=[{ref:'name',label:'姓名',semanticId:'name',value:'',type:'text'},{ref:'resume',label:'上传简历后自动解析',semanticId:'resume',value:'',type:'file',nativeParseCandidate:true}];f.snapshot.nativeResumeParse={available:true,candidates:[{fieldRef:'resume',reason:'file_context'}],inProgress:false};f.snapshot.fingerprint='native-page';f.setBrowser(async(action,args)=>{if(action==='observe')return structuredClone(f.snapshot);if(action==='act'){if(args.actionSpec.kind==='native_parse')return{accepted:true,scope:'native_parser_triggered_requires_new_observation'};f.snapshot.fields[0].value=args.actionSpec.value;return{accepted:true,value:args.actionSpec.value}}return{stopped:true}});let t=f.service.create({clientRequestId:'native-success',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Correct Name',sourceRef:'file:resume.pdf#page=1'}],attachment:{resource:'test'}});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'native_parse',fieldRef:'resume'}]});await wait();t=f.service.status({taskId:t.taskId});assert.equal(t.state,'waiting_native_parse');assert.equal(t.applications[0].operation.state,'awaiting_verification');f.snapshot.fields[0].value='Wrong Name';t=(await f.service.observe({taskId:t.taskId})).task;assert.equal(t.state,'running');assert.deepEqual(t.applications[0].nativeParse,{state:'succeeded',reason:null,changedFieldCount:1});await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();assert.equal(f.snapshot.fields[0].value,'Correct Name');assert.equal(f.service.status({taskId:t.taskId}).applications[0].operation.state,'verified')}));
test('a parser revealed after upload reuses the retained resume and tolerates site defaults',fixture(async f=>{f.snapshot.fields=[{ref:'country',label:'手机号码',semanticId:'mobile',value:'+86',type:'search'},{ref:'identity',label:'个人证件',semanticId:'identity',value:'中国 - 居民身份证',type:'search',sensitive:true},{ref:'none',label:'没有实习经历',semanticId:null,value:'on',checked:true,type:'checkbox'},{ref:'name',label:'姓名',semanticId:'name',value:'',type:'text'},{ref:'resume',label:'简历附件',semanticId:'resume',value:'',receiptText:'resume.pdf 将简历内容解析到表单？解析并覆盖',type:'file',nativeParseCandidate:true}];f.snapshot.nativeResumeParse={available:true,candidates:[{fieldRef:'resume'}],inProgress:false};let sentAttachment='unset';f.setBrowser(async(action,args)=>{if(action==='observe')return structuredClone(f.snapshot);if(action==='act'){sentAttachment=args.attachment;f.snapshot.fields[3].value='Parsed Name';return{accepted:true}}return{stopped:true}});let t=f.service.create({clientRequestId:'native-retained',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Parsed Name',sourceRef:'file:resume.pdf#page=1'}],attachment:{resource:'test'}});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'native_parse',fieldRef:'resume'}]});await wait();assert.equal(sentAttachment,undefined);assert.equal(f.service.get(t.taskId).applications[0].operation.actions[0].reuseUploaded,true);t=(await f.service.observe({taskId:t.taskId})).task;assert.equal(t.applications[0].nativeParse.state,'succeeded')}));
test('native parser no-effect becomes an explicit autonomous-fill fallback without replay',fixture(async f=>{f.snapshot.fields.push({ref:'resume',label:'Parse resume',semanticId:'resume',value:'',type:'file',nativeParseCandidate:true});f.snapshot.nativeResumeParse={available:true,candidates:[{fieldRef:'resume'}],inProgress:false};f.setBrowser(async(action)=>action==='observe'?structuredClone(f.snapshot):{accepted:true});let t=f.service.create({clientRequestId:'native-fallback',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Synthetic Applicant',sourceRef:'file:resume.pdf#page=1'}],attachment:{resource:'test'}});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'native_parse',fieldRef:'resume'}]});await wait();f.service.get(t.taskId).applications[0].operation.verifyUntil=new Date(0).toISOString();t=(await f.service.observe({taskId:t.taskId})).task;assert.equal(t.state,'running');assert.deepEqual(t.applications[0].nativeParse,{state:'failed',reason:'native_parse_no_effect',changedFieldCount:0});assert.equal(t.applications[0].operation.state,'failed')}));
test('native parse survives service restart through read-only reconciliation and is not replayed',fixture(async f=>{f.snapshot.fields.push({ref:'resume',label:'Parse resume',semanticId:'resume',value:'',type:'file',nativeParseCandidate:true});f.snapshot.nativeResumeParse={available:true,candidates:[{fieldRef:'resume'}],inProgress:false};let acts=0;f.setBrowser(async(action)=>{if(action==='act')acts++;return action==='observe'?structuredClone(f.snapshot):{accepted:true}});let t=f.service.create({clientRequestId:'native-restart',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Parsed Name',sourceRef:'file:resume.pdf#page=1'}],attachment:{resource:'test'}});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'native_parse',fieldRef:'resume'}]});await wait();f.snapshot.fields[0].value='Parsed Name';f.restart();t=f.service.status({taskId:t.taskId});assert.equal(t.state,'needs_reconcile');assert.equal(t.applications[0].operation.state,'unknown');t=await f.service.reconcile({taskId:t.taskId});assert.equal(t.state,'running');assert.equal(t.applications[0].operation.state,'verified');assert.equal(t.applications[0].nativeParse.state,'succeeded');assert.equal(acts,1)}));
test('restart queues a task whose last operation was already verified',fixture(async f=>{let t=await ready(f.service);await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();assert.equal(f.service.status({taskId:t.taskId}).applications[0].operation.state,'verified');f.restart();t=f.service.status({taskId:t.taskId});assert.equal(t.state,'queued');assert.match(t.notice,/服务已恢复/);t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;assert.equal(t.state,'running');assert.equal(t.notice,undefined)}));
test('restart cancels a definitely undispatched operation and safely queues the task',fixture(async f=>{let t=await ready(f.service),raw=f.service.get(t.taskId),a=raw.applications[0];a.operation={id:'pending-op',state:'pending',actions:[{kind:'fill',fieldRef:'name',factId:'name',value:'Synthetic Applicant'}],index:0,evidence:[],observationVersion:0};raw.state='executing';f.service.store.write();f.restart();t=f.service.status({taskId:t.taskId});assert.equal(t.state,'queued');assert.equal(t.applications[0].operation.state,'cancelled_before_dispatch')}));
test('native parser cannot overwrite an existing value without a matching authorized fact',fixture(async f=>{f.snapshot.fields=[{ref:'name',label:'姓名',semanticId:'name',value:'User Draft',type:'text'},{ref:'resume',label:'Parse resume',semanticId:'resume',value:'',type:'file',nativeParseCandidate:true}];f.snapshot.nativeResumeParse={available:true,candidates:[{fieldRef:'resume'}],inProgress:false};let t=f.service.create({clientRequestId:'native-protected',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'other',value:'Other Value',sourceRef:'file:resume.pdf#page=1'}],attachment:{resource:'test'}});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await assert.rejects(f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'native_parse',fieldRef:'resume'}]}),/overwrite_existing/)}));
test('reloaded duplicate semantic fields resolve by ordinal or retained value',fixture(async f=>{const snapshot={fields:[{ref:'new-start',semanticId:'dates',group:'education',value:'2020-09'},{ref:'new-end',semanticId:'dates',group:'education',value:'2024-06'}]};assert.equal(f.service.fieldFor(snapshot,{kind:'fill',fieldRef:'old-end',semanticId:'dates',group:'education',semanticOrdinal:1,value:'2024-06'}).ref,'new-end');assert.equal(f.service.fieldFor(snapshot,{kind:'fill',fieldRef:'legacy-end',semanticId:'dates',value:'2024-06'}).ref,'new-end')}));
test('a recycled temporary ref cannot override the action semantic identity',fixture(async f=>{const snapshot={fields:[{ref:'f1',label:'姓名',semanticId:'name',group:null,type:'text',value:'Applicant'},{ref:'fresh-project',label:'项目名称',semanticId:'project_name',group:'projects',type:'text',value:'Project Alpha'}]};const action={kind:'fill',fieldRef:'f1',semanticId:'project_name',semanticOrdinal:0,group:'projects',factId:'project_1_name',value:'Project Alpha'};assert.equal(f.service.fieldFor(snapshot,action).ref,'fresh-project');assert.equal(f.service.actionVerified(snapshot,action),true)}));
test('add actions require a verified increase in the observed section fields',fixture(async f=>{const action={kind:'add',group:'internships',beforeGroupCount:5,beforeFieldCount:8},changed={fields:[...Array.from({length:10},(_,i)=>({ref:`i${i}`,group:'internships'}))]},unchanged={fields:Array.from({length:5},(_,i)=>({ref:`i${i}`,group:'internships'}))};assert.equal(f.service.actionVerified(changed,action),true);assert.equal(f.service.actionVerified(unchanged,action),false);assert.equal(f.service.actionUnchanged(unchanged,action),true)}));
test('legacy add receipts recover only when one safe group contains a repeated row',fixture(async f=>{const action={kind:'add',controlRef:'stale-ref'},one={fields:[{group:'internships',semanticId:'start_end'},{group:'internships',semanticId:'start_end'},{group:'internships',semanticId:'company'}],controls:[{ref:'new-ref',kind:'add',safe:true,group:'internships'}]},two={fields:[{group:'internships',semanticId:'company'},{group:'internships',semanticId:'title'},{group:'internships',semanticId:'company'},{group:'internships',semanticId:'title'}],controls:[{ref:'new-ref',kind:'add',safe:true,group:'internships'}]};assert.equal(f.service.actionVerified(one,action),false);assert.equal(f.service.actionVerified(two,action),true)}));
test('pause/stop before dispatch blocks browser write and stopped task cannot resume',fixture(async f=>{let t=await ready(f.service);await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await f.service.control({taskId:t.taskId,kind:'stop'});await wait();assert.equal(f.calls.filter(c=>c==='act').length,0);f.restart();t=f.service.status({taskId:t.taskId});assert.equal(t.state,'cancelled');assert.throws(()=>f.service.resume({taskId:t.taskId,expectedRevision:t.revision}),/terminal/)}));
test('unknown in-flight effect survives stop/restart and prevents replay',fixture(async f=>{let t=await ready(f.service);f.setBrowser(async action=>{if(action==='act')throw Error('lost_ack');if(action==='observe')return structuredClone(f.snapshot);return{stopped:true}});await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();await f.service.control({taskId:t.taskId,kind:'stop'});f.restart();t=f.service.status({taskId:t.taskId});assert.equal(t.state,'cancelled');assert.equal(t.applications[0].operation.state,'unknown');assert.equal(t.applications[0].budget.actions,1)}));
test('existing values and missing facts are never overwritten or invented',fixture(async f=>{f.snapshot.fields[0].required=true;let t=await ready(f.service);f.snapshot.fields[0].value='User Edit';t=(await f.service.observe({taskId:t.taskId})).task;await assert.rejects(f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]}),/protected/);f.snapshot.fields[0].value='';t=(await f.service.observe({taskId:t.taskId})).task;t=f.service.question({taskId:t.taskId,expectedRevision:t.revision,reason:'missing_facts',text:'请提供学校名称。',missing:['school'],fieldRefs:['name']});const args={taskId:t.taskId,questionId:t.question.id,questionRevision:1,commandId:'answer1',facts:[{id:'school',value:'Test University',sourceRef:'user:answer'}]};assert.equal(f.service.answer(args).duplicate,false);assert.equal(f.service.answer(args).duplicate,true);assert.throws(()=>f.service.answer({...args,facts:[{id:'school',value:'Other',sourceRef:'user:answer'}]}),/conflict/)}));
test('optional, unmarked, manual, and already-answered alternative blanks terminate without waiting',fixture(async f=>{f.snapshot.fields=[{ref:'optional',label:'项目链接（选填）',semanticId:'project_link',value:'',type:'text',required:false,requiredKnown:true},{ref:'unmarked',label:'个人证件',semanticId:'identity',value:'',type:'text',required:false,requiredKnown:false,sensitive:true},{ref:'none',label:'没有实习经历',semanticId:'no_internship',checked:false,type:'checkbox',required:true,requiredKnown:true},{ref:'company',label:'公司名称',semanticId:'company',value:'Example',type:'text',group:'formily-item-internship_list'},{ref:'consent',label:'同意隐私政策',semanticId:'consent',value:'',checked:false,type:'checkbox',required:true,requiredKnown:true,manual:true}];let t=f.service.create({clientRequestId:'optional-finish',targets:[{url:f.snapshot.url,tabId:1}],facts:[]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});const observed=await f.service.observe({taskId:t.taskId});assert.deepEqual(observed.completion,{requiredUnresolved:[],manualFinalSteps:[{ref:'consent',label:'同意隐私政策',semanticId:'consent',type:'checkbox'}],optionalEmpty:[{ref:'optional',label:'项目链接（选填）',semanticId:'project_link',type:'text'}],unmarkedEmpty:[{ref:'unmarked',label:'个人证件',semanticId:'identity',type:'text'}],satisfiedAlternatives:[{ref:'none',label:'没有实习经历',semanticId:'no_internship',type:'checkbox'}],canAdvance:false,completionVerifiable:false});for(const fieldRefs of [['unmarked'],['consent'],['none']])assert.throws(()=>f.service.question({taskId:t.taskId,expectedRevision:observed.task.revision,reason:'missing_facts',text:'请处理该字段。',missing:['identity'],fieldRefs}),/question_not_required/);t=f.service.finish({taskId:t.taskId,expectedRevision:observed.task.revision,outcome:'partial',missing:['identity','consent'],unsupported:[]});assert.equal(t.state,'finished');assert.equal(t.applications[0].outcome,'partial');assert.deepEqual(t.applications[0].missing,[]);assert.deepEqual(t.applications[0].unsupported,['manual:consent'])}));
test('a site validation error promotes an unmarked empty field to a required blocker',fixture(async f=>{f.snapshot.fields=[{ref:'school',label:'学校名称',semanticId:'school',value:'',type:'text',required:false,requiredKnown:false}];f.snapshot.errors=['学校名称：请输入必填内容'];let t=f.service.create({clientRequestId:'dynamic-required',targets:[{url:f.snapshot.url,tabId:1}],facts:[]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});const observed=await f.service.observe({taskId:t.taskId});assert.deepEqual(observed.completion.requiredUnresolved,[{ref:'school',label:'学校名称',semanticId:'school',type:'text'}]);t=f.service.question({taskId:t.taskId,expectedRevision:observed.task.revision,reason:'missing_facts',text:'请提供学校名称。',missing:['school'],fieldRefs:['school']});assert.equal(t.state,'waiting_user')}));
test('extension emergency stop closes the task and blocks later work',fixture(async f=>{let t=await ready(f.service),a=t.applications[0];const receipt=f.service.browserEvent({event:'emergency_stop',tabId:a.tabId,targetURL:a.url,runId:a.runId});assert.equal(receipt.accepted,true);t=f.service.status({taskId:t.taskId});assert.equal(t.state,'cancelled');assert.equal(t.control.browser,'confirmed');assert.equal(t.control.source,'extension');assert.throws(()=>f.service.claim({taskId:t.taskId,expectedRevision:t.revision}),/terminal/)}));
test('verified structure becomes reusable experience only after repeated success and stores no values',fixture(async f=>{async function complete(key){let t=f.service.create({clientRequestId:key,targets:[{url:'https://example.test/apply',tabId:1}],facts:[{id:'name',value:'Synthetic Applicant',sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();f.snapshot.canAdvance=true;f.snapshot.completionVerifiable=true;t=f.service.status({taskId:t.taskId});t=(await f.service.observe({taskId:t.taskId})).task;return f.service.finish({taskId:t.taskId,expectedRevision:t.revision,outcome:'ready_for_review'})}
 await complete('experience-one');f.snapshot.fields[0].value='';f.snapshot.canAdvance=false;f.snapshot.completionVerifiable=false;let t=f.service.create({clientRequestId:'probe-one',targets:[{url:'https://example.test/apply',tabId:1}],facts:[{id:'name',value:'Different Private Value',sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});let observed=await f.service.observe({taskId:t.taskId});assert.equal(observed.experience,null);await f.service.control({taskId:t.taskId,kind:'stop'});
 f.snapshot.fields[0].value='';f.snapshot.canAdvance=false;f.snapshot.completionVerifiable=false;await complete('experience-two');f.snapshot.fields[0].value='';f.snapshot.canAdvance=false;f.snapshot.completionVerifiable=false;t=f.service.create({clientRequestId:'probe-two',targets:[{url:'https://example.test/apply',tabId:1}],facts:[{id:'name',value:'Another Private Value',sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});observed=await f.service.observe({taskId:t.taskId});assert.equal(observed.experience.status,'reusable');assert.equal(observed.experience.successCount,2);assert.equal(JSON.stringify(observed.experience).includes('Synthetic Applicant'),false);assert.equal(JSON.stringify(observed.experience).includes('Private Value'),false);
 const feedback=f.service.experience_feedback({taskId:t.taskId,reason:'用户确认字段语义错误'});assert.equal(feedback.experience.status,'suspended');observed=await f.service.observe({taskId:t.taskId});assert.equal(observed.experience,null)}));
test('partial results accumulate verified fields and reusable suggestions execute through the normal guard',fixture(async f=>{async function partial(key,id,value){f.snapshot.url=`https://example.test/jobs/${id}/apply`;f.snapshot.fields[0].ref=`name-${id}`;f.snapshot.fields[0].value='';f.snapshot.canAdvance=false;f.snapshot.completionVerifiable=false;let t=f.service.create({clientRequestId:key,targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value,sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:f.snapshot.fields[0].ref,factId:'name'}]});await wait();t=(await f.service.observe({taskId:t.taskId})).task;return f.service.finish({taskId:t.taskId,expectedRevision:t.revision,outcome:'partial',missing:['manual_consent']})}await partial('partial-one','11111','First Private');await partial('partial-two','22222','Second Private');f.snapshot.url='https://example.test/jobs/33333/apply';f.snapshot.fields[0].ref='new-name-ref';f.snapshot.fields[0].value='';let t=f.service.create({clientRequestId:'partial-reuse',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Third Private',sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});const observed=await f.service.observe({taskId:t.taskId});assert.equal(observed.experience.match,'exact');assert.equal(observed.experience.suggestedActions.length,1);assert.equal(JSON.stringify(observed.experience).includes('Third Private'),false);await f.service.apply({taskId:t.taskId,expectedRevision:observed.task.revision,actions:observed.experience.suggestedActions});await wait();assert.equal(f.snapshot.fields[0].value,'Third Private');assert.equal(f.service.status({taskId:t.taskId}).applications[0].operation.state,'verified')}));
test('a reusable field strategy is automatically suspended after read-only reconciliation proves no effect',fixture(async f=>{async function train(key,value){f.snapshot.fields[0].value='';let t=f.service.create({clientRequestId:key,targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value,sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();t=(await f.service.observe({taskId:t.taskId})).task;return f.service.finish({taskId:t.taskId,expectedRevision:t.revision,outcome:'partial',missing:['manual']})}await train('failure-train-one','First');await train('failure-train-two','Second');f.snapshot.fields[0].value='';let t=f.service.create({clientRequestId:'failure-probe',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Third',sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});let observed=await f.service.observe({taskId:t.taskId});const actions=observed.experience.suggestedActions;f.setBrowser(async action=>{if(action==='observe')return structuredClone(f.snapshot);if(action==='act')throw Error('site_rejected_value');return{stopped:true}});await f.service.apply({taskId:t.taskId,expectedRevision:observed.task.revision,actions});await wait();t=await f.service.reconcile({taskId:t.taskId});assert.equal(t.state,'needs_attention');t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});observed=await f.service.observe({taskId:t.taskId});assert.equal(observed.experience,null)}));
test('transport ambiguity does not downgrade a field experience as a semantic failure',fixture(async f=>{assert.equal(f.service.semanticExperienceFailure('lost_ack'),false);assert.equal(f.service.semanticExperienceFailure('browser_disconnected'),false);assert.equal(f.service.semanticExperienceFailure('site_rejected_value'),true);assert.equal(f.service.semanticExperienceFailure('field_detached'),true)}));
test('radio and non-legal checkbox actions are verified while manual consent stays blocked',fixture(async f=>{f.snapshot.fields=[{ref:'remote',label:'是否接受异地办公',optionLabel:'是',semanticId:'remote',type:'radio',value:'',checked:false},{ref:'updates',label:'接收岗位进度通知',optionLabel:'接收',semanticId:'updates',type:'checkbox',value:'',checked:false},{ref:'consent',label:'本人声明以上信息真实',optionLabel:'同意',semanticId:'consent',type:'checkbox',value:'',checked:false,manual:true}];f.snapshot.fingerprint='choices';f.setBrowser(async(action,args)=>{if(action==='observe')return structuredClone(f.snapshot);if(action==='act'){const field=f.snapshot.fields.find(item=>item.ref===args.actionSpec.fieldRef);field.checked=true;field.value=args.actionSpec.value;return{accepted:true,fieldRef:field.ref,value:field.value,documentEpoch:f.snapshot.documentEpoch}}return{stopped:true}});let t=f.service.create({clientRequestId:'choices',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'remote',value:'是',sourceRef:'user:answer'},{id:'updates',value:'true',sourceRef:'user:answer'},{id:'consent',value:'true',sourceRef:'user:answer'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await assert.rejects(f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'check',fieldRef:'consent',factId:'consent'}]}),/sensitive/);t=f.service.status({taskId:t.taskId});await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'choose',fieldRef:'remote',factId:'remote'},{kind:'check',fieldRef:'updates',factId:'updates'}]});await wait();t=f.service.status({taskId:t.taskId});assert.equal(t.applications[0].operation.state,'verified')}));
test('reconciliation completes a checkbox clear that changed the page before its receipt failed',fixture(async f=>{f.snapshot.fields=[{ref:'none',label:'没有实习经历',semanticId:'internship-none',type:'checkbox',value:'on',checked:true}];f.snapshot.fingerprint='checkbox-clear';f.setBrowser(async(action,args)=>{if(action==='observe')return structuredClone(f.snapshot);if(action==='act'){f.snapshot.fields[0].checked=false;f.snapshot.fields[0].value='';throw Error('site_rejected_value')}return{stopped:true}});let t=f.service.create({clientRequestId:'clear-checkbox',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'has_internship',value:'false',sourceRef:'file:resume.pdf#page=2'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'check',fieldRef:'none',factId:'has_internship'}]});await wait();t=f.service.status({taskId:t.taskId});assert.equal(t.state,'needs_reconcile');t=await f.service.reconcile({taskId:t.taskId});assert.equal(t.state,'running');assert.equal(t.applications[0].operation.state,'verified');assert.equal(t.applications[0].operation.index,1);assert.equal(t.applications[0].operation.total,1);assert.equal(t.applications[0].operation.error,undefined)}));
test('reconciliation marks a rejected selection with no page effect as retryable',fixture(async f=>{f.snapshot.fields=[{ref:'degree',label:'学历',semanticId:'degree',type:'search',value:''}];f.snapshot.fingerprint='select-no-effect';f.setBrowser(async(action)=>{if(action==='observe')return structuredClone(f.snapshot);if(action==='act')throw Error('ambiguous_option');return{stopped:true}});let t=f.service.create({clientRequestId:'select-no-effect',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'degree',value:'本科',sourceRef:'file:resume.pdf#page=1'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'select',fieldRef:'degree',factId:'degree'}]});await wait();t=await f.service.reconcile({taskId:t.taskId});assert.equal(t.state,'needs_attention');assert.equal(t.applications[0].operation.state,'failed');t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});assert.equal(t.state,'running')}));
test('reconciliation can prove no effect after extension reload changed the document epoch',fixture(async f=>{f.snapshot.fields=[{ref:'degree',label:'学历',semanticId:'degree',type:'search',value:''}];f.snapshot.fingerprint='select-reload';f.setBrowser(async(action)=>{if(action==='observe')return structuredClone(f.snapshot);if(action==='act'){f.snapshot.documentEpoch='reloaded-document';throw Error('ambiguous_option')}return{stopped:true}});let t=f.service.create({clientRequestId:'select-reload',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'degree',value:'本科',sourceRef:'file:resume.pdf#page=1'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'select',fieldRef:'degree',factId:'degree'}]});await wait();t=await f.service.reconcile({taskId:t.taskId});assert.equal(t.applications[0].operation.state,'failed');assert.equal(t.state,'needs_attention')}));
test('custom selection budget is scoped to the deployed strategy version',fixture(async f=>{f.snapshot.fields=[{ref:'degree',label:'学历',semanticId:'degree',type:'search',value:''}];f.snapshot.fingerprint='versioned-select';f.setBrowser(async(action)=>action==='observe'?structuredClone(f.snapshot):Promise.reject(Error('ambiguous_option')));let t=f.service.create({clientRequestId:'versioned-select',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'degree',value:'本科',sourceRef:'file:resume.pdf#page=1'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'select',fieldRef:'degree',factId:'degree'}]});assert.equal(Object.keys(f.service.get(t.taskId).applications[0].budget.strategies).some(key=>key.endsWith(':degree:custom-select-v6')),true)}));
test('normalized site enum is retained for fresh verification',fixture(async f=>{f.snapshot.fields=[{ref:'education-type',label:'学历类型',semanticId:'education-type',type:'search',value:''}];f.snapshot.fingerprint='normalized-select';f.setBrowser(async(action)=>{if(action==='observe')return structuredClone(f.snapshot);f.snapshot.fields[0].value='全日制';return{accepted:true,value:'全日制',normalized:true,documentEpoch:f.snapshot.documentEpoch}});let t=f.service.create({clientRequestId:'normalized-select',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'education_type',value:'统招全日制',sourceRef:'file:resume.pdf#page=1'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'select',fieldRef:'education-type',factId:'education_type'}]});await wait();t=(await f.service.observe({taskId:t.taskId})).task;assert.equal(t.state,'running');assert.equal(f.service.get(t.taskId).applications[0].operation.actions[0].acceptedValue,'全日制')}));
test('multiple applications retain their frozen order and stop cancels the remainder',fixture(async f=>{f.setBrowser(async(action,args)=>{if(action==='observe')return{...structuredClone(f.snapshot),url:args.targetURL};if(action==='act'){f.snapshot.fields[0].value=args.actionSpec.value;return{accepted:true,fieldRef:'name',value:args.actionSpec.value,documentEpoch:f.snapshot.documentEpoch}}return{stopped:true}});let t=f.service.create({clientRequestId:'batch',targets:[{url:'https://example.test/first',tabId:1},{url:'https://example.test/second',tabId:2}],facts:[{id:'name',value:'Synthetic Applicant',sourceRef:'synthetic:test'}]});assert.deepEqual(t.applications.map(item=>item.url),['https://example.test/first','https://example.test/second']);t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();f.snapshot.canAdvance=true;f.snapshot.completionVerifiable=true;t=f.service.status({taskId:t.taskId});t=(await f.service.observe({taskId:t.taskId})).task;t=f.service.finish({taskId:t.taskId,expectedRevision:t.revision,outcome:'ready_for_review'});assert.equal(t.current,1);assert.equal(t.state,'queued');t=await f.service.control({taskId:t.taskId,kind:'stop'});assert.equal(t.state,'cancelled');assert.equal(t.applications[0].outcome,'ready_for_review');assert.equal(t.applications[1].outcome,'cancelled')}));

test('resume strategy is explicit and prevents field experience from racing the site parser',fixture(async f=>{
 f.snapshot.fields.push({ref:'resume',label:'上传简历并解析',semanticId:'resume',value:'',type:'file',nativeParseCandidate:true});
 f.snapshot.nativeResumeParse={available:true,candidates:[{fieldRef:'resume'}],inProgress:false};
 let t=f.service.create({clientRequestId:'resume-order',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Synthetic Applicant',sourceRef:'synthetic:test'}],attachment:{resource:'test'}});
 t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});
 const observed=await f.service.observe({taskId:t.taskId});
 assert.deepEqual(observed.resumeStrategy,{kind:'native_parse',fieldRef:'resume',isolated:true});
 await assert.rejects(f.service.apply({taskId:t.taskId,expectedRevision:observed.task.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]}),/native_resume_strategy_required/);
}));

test('a hidden parser requires one isolated upload before other field actions',fixture(async f=>{
 f.snapshot.fields.push({ref:'resume',label:'简历附件',semanticId:'resume',value:'',receiptText:'',type:'file',nativeParseCandidate:false});
 f.snapshot.nativeResumeParse={available:false,candidates:[],inProgress:false};
 let t=f.service.create({clientRequestId:'resume-upload-order',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Synthetic Applicant',sourceRef:'synthetic:test'}],attachment:{resource:'test'}});
 t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});
 const observed=await f.service.observe({taskId:t.taskId});
 assert.deepEqual(observed.resumeStrategy,{kind:'upload_then_reobserve',fieldRef:'resume',isolated:true});
 await assert.rejects(f.service.apply({taskId:t.taskId,expectedRevision:observed.task.revision,actions:[{kind:'upload',fieldRef:'resume'},{kind:'fill',fieldRef:'name',factId:'name'}]}),/isolated_resume_upload_required/);
}));

test('one service call executes and finishes an exact reusable page without another agent decision',fixture(async f=>{
 async function train(key,value){f.snapshot.fields[0].value='';let t=f.service.create({clientRequestId:key,targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value,sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();t=(await f.service.observe({taskId:t.taskId})).task;f.service.finish({taskId:t.taskId,expectedRevision:t.revision,outcome:'partial'})}
 await train('fast-train-one','First');await train('fast-train-two','Second');f.snapshot.fields[0].value='';f.calls.length=0;let t=f.service.create({clientRequestId:'fast-known',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Third',sourceRef:'synthetic:test'}]});const result=await f.service.run_experience({taskId:t.taskId,expectedRevision:t.revision});assert.equal(result.path,'experience');assert.equal(result.outcome,'partial');assert.equal(result.actionCount,1);assert.equal(result.task.state,'finished');assert.equal(f.snapshot.fields[0].value,'Third');assert.equal(f.calls.filter(action=>action==='act').length,1);assert.equal(result.finalSubmitAllowed,false)
}));

test('experience execution returns a running adaptive handoff on a new or changed page',fixture(async f=>{const t=f.service.create({clientRequestId:'fast-cold',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Applicant',sourceRef:'synthetic:test'}]}),result=await f.service.run_experience({taskId:t.taskId,expectedRevision:t.revision});assert.equal(result.path,'adaptive');assert.equal(result.reason,'experience_not_reusable');assert.equal(result.task.state,'running');assert.equal(f.calls.includes('act'),false)}));

test('known-page execution lets the native parser run once and corrects its values from the same resume facts',fixture(async f=>{
 f.snapshot.fields.push({ref:'resume',label:'上传简历并解析',semanticId:'resume',value:'',receiptText:'',type:'file',nativeParseCandidate:true});f.snapshot.nativeResumeParse={available:true,candidates:[{fieldRef:'resume'}],inProgress:false};
 f.setBrowser(async(action,args)=>{f.calls.push(action);f.requests.push({action,args:structuredClone(args)});if(action==='observe')return structuredClone(f.snapshot);if(action==='act'){if(args.actionSpec.kind==='native_parse'){f.snapshot.fields[0].value='网站误解析';f.snapshot.fields[1].value='resume.pdf';f.snapshot.fields[1].receiptText='resume.pdf';return{accepted:true}}f.snapshot.fields[0].value=args.actionSpec.value;return{accepted:true}}return{stopped:true}});
 async function train(key,value){f.snapshot.fields[0].value='';f.snapshot.fields[1].value='existing.pdf';f.snapshot.fields[1].receiptText='existing.pdf';let t=f.service.create({clientRequestId:key,targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value,sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();t=(await f.service.observe({taskId:t.taskId})).task;f.service.finish({taskId:t.taskId,expectedRevision:t.revision,outcome:'partial'})}
 await train('parser-fast-one','First');await train('parser-fast-two','Second');f.snapshot.fields[0].value='';f.snapshot.fields[1].value='';f.snapshot.fields[1].receiptText='';f.calls.length=0;let t=f.service.create({clientRequestId:'parser-fast-known',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Resume Truth',sourceRef:'file:resume.pdf#page=1'}],attachment:{resource:'test'}});const result=await f.service.run_experience({taskId:t.taskId,expectedRevision:t.revision});assert.equal(result.path,'experience');assert.equal(result.task.state,'finished');assert.equal(f.snapshot.fields[0].value,'Resume Truth');assert.deepEqual(f.calls.filter(action=>action==='act').length,2);assert.equal(f.service.get(t.taskId).applications[0].nativeParse.state,'succeeded')
}));

test('known-page execution recognizes automatic parsing after upload and corrects it without an agent turn',fixture(async f=>{
 f.snapshot.fields.push({ref:'resume',label:'简历附件',semanticId:'resume',value:'',receiptText:'',type:'file',nativeParseCandidate:false});f.snapshot.nativeResumeParse={available:false,candidates:[],inProgress:false};
 f.setBrowser(async(action,args)=>{f.calls.push(action);f.requests.push({action,args:structuredClone(args)});if(action==='observe')return structuredClone(f.snapshot);if(action==='act'){if(args.actionSpec.kind==='upload'){f.snapshot.fields[0].value='自动解析错误';f.snapshot.fields[1].value='resume.pdf';f.snapshot.fields[1].receiptText='resume.pdf';return{accepted:true}}f.snapshot.fields[0].value=args.actionSpec.value;return{accepted:true}}return{stopped:true}});
 async function train(key,value){f.snapshot.fields[0].value='';f.snapshot.fields[1].value='existing.pdf';f.snapshot.fields[1].receiptText='existing.pdf';let t=f.service.create({clientRequestId:key,targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value,sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'fill',fieldRef:'name',factId:'name'}]});await wait();t=(await f.service.observe({taskId:t.taskId})).task;f.service.finish({taskId:t.taskId,expectedRevision:t.revision,outcome:'partial'})}
 await train('auto-fast-one','First');await train('auto-fast-two','Second');f.snapshot.fields[0].value='';f.snapshot.fields[1].value='';f.snapshot.fields[1].receiptText='';f.calls.length=0;const t=f.service.create({clientRequestId:'auto-fast-known',targets:[{url:f.snapshot.url,tabId:1}],facts:[{id:'name',value:'Resume Truth',sourceRef:'file:resume.pdf#page=1'}],attachment:{resource:'test'}}),result=await f.service.run_experience({taskId:t.taskId,expectedRevision:t.revision});assert.equal(result.path,'experience');assert.equal(result.task.state,'finished');assert.equal(f.snapshot.fields[0].value,'Resume Truth');assert.equal(f.calls.filter(action=>action==='act').length,2);const native=f.service.get(t.taskId).applications[0].nativeParse;assert.equal(native.state,'succeeded');assert.equal(native.reason,'automatic_after_upload')
}));

test('a retained matching resume receipt suppresses a duplicate experienced upload',fixture(async f=>{
 f.snapshot.fields=[{ref:'resume',label:'简历附件',semanticId:'resume',value:'',receiptText:'',type:'file'}];f.setBrowser(async(action,args)=>{if(action==='observe')return structuredClone(f.snapshot);if(action==='act'){f.snapshot.fields[0].value='resume.pdf';f.snapshot.fields[0].receiptText='resume.pdf';return{accepted:true}}return{stopped:true}});
 async function train(key){f.snapshot.fields[0].value='';f.snapshot.fields[0].receiptText='';let t=f.service.create({clientRequestId:key,targets:[{url:f.snapshot.url,tabId:1}],facts:[],attachment:{resource:'test'}});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});t=(await f.service.observe({taskId:t.taskId})).task;await f.service.apply({taskId:t.taskId,expectedRevision:t.revision,actions:[{kind:'upload',fieldRef:'resume'}]});await wait();t=(await f.service.observe({taskId:t.taskId})).task;f.service.finish({taskId:t.taskId,expectedRevision:t.revision,outcome:'partial'})}
 await train('upload-one');await train('upload-two');let t=f.service.create({clientRequestId:'upload-preserved',targets:[{url:f.snapshot.url,tabId:1}],facts:[],attachment:{resource:'test'}});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});const observed=await f.service.observe({taskId:t.taskId});assert.equal(observed.experience.match,'exact');assert.deepEqual(observed.experience.suggestedActions,[]);assert.equal(observed.experience.preserved.length,1)
}));

test('a zero-field detail page cannot finish and a safe start control hands off to the application URL',fixture(async f=>{
 const detail='https://example.test/jobs/12345',apply='https://example.test/jobs/12345/apply';
 f.snapshot.url=detail;f.snapshot.formStage='detail';f.snapshot.fields=[];f.snapshot.controls=[{ref:'start',label:'立即申请',kind:'start',safe:true}];f.snapshot.canAdvance=false;f.snapshot.completionVerifiable=false;
 f.setBrowser(async(action,args)=>{if(action==='observe')return structuredClone(f.snapshot);if(action==='act'){assert.equal(args.actionSpec.kind,'start');f.snapshot.url=apply;f.snapshot.formStage='apply';f.snapshot.documentEpoch='application-document';f.snapshot.fields=[{ref:'name',label:'姓名',semanticId:'name',value:'',type:'text'}];f.snapshot.controls=[];return{accepted:true,url:apply,tabId:2,documentEpoch:'detail-document'}}return{stopped:true}});
 let t=f.service.create({clientRequestId:'detail-start',targets:[{url:detail,tabId:1}],facts:[{id:'name',value:'Synthetic Applicant',sourceRef:'synthetic:test'}]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});let observed=await f.service.observe({taskId:t.taskId});
 assert.throws(()=>f.service.finish({taskId:t.taskId,expectedRevision:observed.task.revision,outcome:'partial'}),/application_form_not_observed/);
 await f.service.apply({taskId:t.taskId,expectedRevision:observed.task.revision,actions:[{kind:'start',controlRef:'start'}]});await wait();observed=await f.service.observe({taskId:t.taskId});
 assert.equal(observed.task.currentApplication.url,apply);assert.equal(observed.task.applications[0].tabId,2);assert.equal(observed.snapshot.formStage,'apply');assert.equal(observed.task.applications[0].operation.state,'verified');
}));

test('a verified start click with no page effect stays retryable within the page budget',fixture(async f=>{
 const detail='https://example.test/jobs/slow-start';
 f.snapshot.url=detail;f.snapshot.formStage='detail';f.snapshot.fields=[];f.snapshot.controls=[{ref:'start',label:'立即投递',kind:'start',safe:true}];f.snapshot.canAdvance=false;f.snapshot.completionVerifiable=false;
 f.setBrowser(async(action,args)=>action==='observe'?structuredClone(f.snapshot):action==='act'?{accepted:true,url:detail,documentEpoch:f.snapshot.documentEpoch}:{stopped:true});
 let t=f.service.create({clientRequestId:'detail-start-retry',targets:[{url:detail,tabId:1}],facts:[]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});let observed=await f.service.observe({taskId:t.taskId});
 await f.service.apply({taskId:t.taskId,expectedRevision:observed.task.revision,actions:[{kind:'start',controlRef:'start'}]});await wait();observed=await f.service.observe({taskId:t.taskId});
 assert.equal(observed.task.state,'running');assert.equal(observed.task.applications[0].operation.state,'failed');assert.equal(observed.task.applications[0].operation.error,'application_start_no_effect');assert.equal(observed.task.applications[0].budget.replanCount,1);
}));

test('a same-document prerequisite modal verifies an application start',fixture(async f=>{
 const detail='https://example.test/jobs/modal-start';
 f.snapshot.url=detail;f.snapshot.pageState='normal';f.snapshot.formStage='detail';f.snapshot.fields=[];f.snapshot.controls=[{ref:'start',label:'立即投递',kind:'start',safe:true}];f.snapshot.canAdvance=false;f.snapshot.completionVerifiable=false;
 f.setBrowser(async(action,args)=>{if(action==='observe')return structuredClone(f.snapshot);if(action==='act'){f.snapshot.pageState='resume_prerequisite';f.snapshot.controls=[{ref:'edit',label:'编辑',kind:'start',safe:true}];return{accepted:true,url:detail,documentEpoch:f.snapshot.documentEpoch}}return{stopped:true}});
 let t=f.service.create({clientRequestId:'modal-start',targets:[{url:detail,tabId:1}],facts:[]});t=f.service.claim({taskId:t.taskId,expectedRevision:t.revision});let observed=await f.service.observe({taskId:t.taskId});
 await f.service.apply({taskId:t.taskId,expectedRevision:observed.task.revision,actions:[{kind:'start',controlRef:'start'}]});await wait();observed=await f.service.observe({taskId:t.taskId});
 assert.equal(observed.task.state,'running');assert.equal(observed.task.applications[0].operation.state,'verified');assert.equal(observed.snapshot.pageState,'resume_prerequisite');
}));
