import WebSocket from 'ws';
import {randomUUID} from 'node:crypto';
export class AtollClient {
 constructor(base,auth=''){this.base=base;this.auth=typeof auth==='string'?{cookie:auth}:auth??{};this.cookie=this.auth.cookie??'';this.authorization=this.auth.authorization??'';this.frames=[];this.closed=false;}
 headers(extra={}){return{...extra,...(this.cookie?{cookie:this.cookie}:{}),...(this.authorization?{authorization:this.authorization}:{})}}
 async http(path,body){const r=await fetch(this.base+path,{method:body?'POST':'GET',headers:this.headers({'content-type':'application/json'}),body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(8000)});const text=await r.text();let value;try{value=JSON.parse(text)}catch{value={text}};const cookies=r.headers.getSetCookie();if(cookies.length)this.cookie=cookies.map(x=>x.split(';')[0]).join('; ');if(!r.ok)throw Object.assign(new Error(`HTTP ${r.status} ${path}`),{detail:value});return value;}
 async login(email,password){this.identity=await this.http('/api/identity/login',{email,password});return this.identity;}
 async open(channel){this.channel=channel;this.ws=new WebSocket(this.base.replace(/^http/,'ws')+'/ws',{headers:this.headers()});this.ws.on('message',buf=>{try{this.frames.push(JSON.parse(buf))}catch{}});this.ws.on('close',()=>this.closed=true);await new Promise((resolve,reject)=>{this.ws.once('open',resolve);this.ws.once('error',reject)});const r=await this.frame('attach',{since:{},focus:channel,history_protocol:5,generation:1});if(r.frame_type==='error')throw Object.assign(new Error('attach rejected'),{detail:r.payload});return r;}
 async wait(test,ms=15000){const until=Date.now()+ms;while(Date.now()<until){const v=this.frames.find(test);if(v)return v;if(this.closed)throw new Error('connection closed');await new Promise(r=>setTimeout(r,15));}throw new Error('Atoll response timeout; outcome unknown');}
 async frame(type,payload){const ref=randomUUID();this.ws.send(JSON.stringify({v:5,frame_type:type,ref,payload}));return this.wait(x=>x.ref===ref&&['receipt','error'].includes(x.frame_type));}
 async request(type,payload={},audience='system',channel=this.channel){const ack=await this.frame('submit',{channel_id:channel,msg_type:type,kind:'request',visibility:'public',audience:[audience],payload});if(ack.frame_type==='error')return {ok:false,transport:ack.payload};const requestId=ack.payload.message_id;const terminal=await this.wait(x=>x.frame_type==='feed'&&x.payload?.envelope?.kind==='response'&&x.payload.envelope.parent_id===requestId&&['completed','failed'].includes(x.payload.envelope.payload?.status));const response=terminal.payload.envelope;const request=this.frames.find(x=>x.payload?.envelope?.id===requestId)?.payload.envelope;return {ok:response.payload.status==='completed',requestId,request,response,body:response.payload};}
 close(){this.ws?.close();}
}
export function unwrap(result){if(!result.ok)throw Object.assign(new Error('Atoll request failed'),{detail:result});let v=result.body;return v.value??v;}
