import fs from'node:fs';import readline from'node:readline';import{BrowserBridge}from'./browser-bridge.mjs';import{Attachments}from'./attachments.mjs';import{CvMaxService}from'./service.mjs';import{RecipeRegistryClient}from'./recipe-registry-client.mjs';
const file=process.argv[2];if(!file)throw Error('Explicit private instance config required');const cfg=JSON.parse(fs.readFileSync(file));let service;const bridge=new BrowserBridge({...cfg.browser,timeoutMs:20000,leaseMs:8000,onEvent:event=>service.browserEvent(event)});const recipeRegistry=cfg.recipeRegistry?new RecipeRegistryClient(cfg.recipeRegistry):null;
service=new CvMaxService({file:cfg.stateFile,browser:(a,p)=>bridge.command(a,p),browserStatus:()=>bridge.status(),attachments:new Attachments(cfg.attachments),recipeRegistry,localPolicy:cfg.localPolicy});
const actionVariant=(kinds,properties,required)=>({type:'object',properties:{kind:{type:'string',enum:kinds},...properties},required:['kind',...required],additionalProperties:false});
const actionSchema={oneOf:[
 actionVariant(['fill','select','choose','check'],{fieldRef:{type:'string'},factId:{type:'string'}},['fieldRef','factId']),
 actionVariant(['upload','native_parse'],{fieldRef:{type:'string'}},['fieldRef']),
 actionVariant(['next','start'],{controlRef:{type:'string'}},['controlRef']),
 actionVariant(['add','section'],{controlRef:{type:'string'},section:{type:'string'},sectionKey:{type:'string'}},['controlRef','section','sectionKey']),
 actionVariant(['activate'],{controlRef:{type:'string'},activationMode:{type:'string',enum:['isolated_pointer','main_world_pointer']},expectedPostcondition:{type:'string',enum:['dialog_closed','surface_changed','fields_increased']},purpose:{type:'string'}},['controlRef','activationMode','expectedPostcondition'])
]};
const actionArraySchema={type:'array',items:actionSchema};
const definitions={health:{},metrics_summary:{},maintenance:{},data_delete:{kind:'string',id:'string'},current:{},request_save:{clientRequestId:'string',learningMode:'string',links:'array',currentPage:'boolean',facts:'array',taskAnswers:'array',attachment:'object',resume:'object',profileRevision:'number'},request_get:{clientRequestId:'string'},resume_save:{saveRequestId:'string',resumeId:'string',expectedRevision:'number',name:'string',facts:'array',attachment:'object'},resume_list:{},resume_get:{resumeId:'string'},profile_save:{saveRequestId:'string',expectedRevision:'number',facts:'array'},profile_get:{},task_context:{taskId:'string'},recipe_feedback:{taskId:'string',reason:'string',transitionId:'string'},yield_task:{taskId:'string',expectedRevision:'number',commandId:'string'},continuation_receipt:{taskId:'string',commandId:'string',outcome:'string',timerId:'string'},report:{taskId:'string'},wake_receipt:{taskId:'string',commandId:'string',outcome:'string',messageId:'string'},create:{clientRequestId:'string',targets:'array',facts:'array',attachment:'object',resume:'object'},status:{taskId:'string',clientRequestId:'string'},claim:{taskId:'string',expectedRevision:'number'},run_recipe:{taskId:'string',expectedRevision:'number'},observe:{taskId:'string'},refresh:{taskId:'string',expectedRevision:'number'},navigate:{taskId:'string',expectedRevision:'number',purpose:'string',targetURL:'string'},apply:{taskId:'string',expectedRevision:'number',actions:actionArraySchema},reconcile:{taskId:'string'},control:{taskId:'string',kind:'string'},resume:{taskId:'string',expectedRevision:'number'},question:{taskId:'string',expectedRevision:'number',reason:'string',text:'string',missing:'array',fieldRefs:'array'},answer:{taskId:'string',questionId:'string',questionRevision:'number',commandId:'string',facts:'array',acknowledged:'boolean'},finish:{taskId:'string',expectedRevision:'number',outcome:'string',missing:'array',unsupported:'array'},finish_unavailable:{taskId:'string',expectedRevision:'number'}};
const requiredFields={run_recipe:['taskId','expectedRevision']};
const descriptions={task_context:'CvMax task_context. Returns the frozen facts for the current task. Never expose values in narration or submit the application.',run_recipe:'CvMax run_recipe. Replays only verified Recipe transitions. Unknown pages return learning_unavailable without invoking the removed learner. Never final submit.'};
const schemaFor=value=>typeof value==='string'?{type:value,...value==='array'?{items:{}}:{}}:value;
const tools=Object.entries(definitions).map(([name,fields])=>({name,description:descriptions[name]??`CvMax ${name}. Fill and verify only. Never final submit. Unknown page effects require reconciliation.`,inputSchema:{type:'object',properties:Object.fromEntries(Object.entries(fields).map(([k,value])=>[k,schemaFor(value)])),...requiredFields[name]&&{required:requiredFields[name]},additionalProperties:false}}));
readline.createInterface({input:process.stdin}).on('line',async line=>{let q;try{q=JSON.parse(line);let result;if(q.method==='server/discover')result={supportedVersions:['2026-07-28'],capabilities:{tools:{}},instructions:'CvMax private application service. No final-submit operation.',ttlMs:0,cacheScope:'private',_meta:{'io.modelcontextprotocol/serverInfo':{name:'cvmax',version:'0.9.0'}}};else if(q.method==='tools/list')result={tools,ttlMs:0,cacheScope:'private'};else if(q.method==='tools/call'){const name=q.params.name,args=q.params.arguments??{};if(!definitions[name]||Object.keys(args).some(k=>!definitions[name][k]))throw Error('unknown_method_or_argument');let data=await service[name](args),content=[{type:'text',text:JSON.stringify({tool:name,status:'completed'})}];result={resultType:'complete',content,structuredContent:data,isError:false}}else throw Error('method_not_found');process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:q.id,result})+'\n')}catch(e){if(q?.id!==undefined)process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:q.id,error:{code:-32602,message:e.message}})+'\n')}});
let closing=false;async function close(){if(closing)return;closing=true;await bridge.close();process.exit(0)}process.stdin.on('end',close);process.on('SIGTERM',close);process.on('SIGINT',close);
